### PR TITLE
Wip/salsah1 login

### LINKED ISSUE #474: SALSAH remembers username and password after logout
If you log into SALSAH, log out, and then click the login button again, the username and password are automatically filled in. This is a security flaw.

After you log in, SALSAH should forget your password. After you log out, it should forget your username, too.

@loicjaouen, would you like to take this one?

### PR DESCRIPTION
**Pull request by loicjaouen**
fixes #474

### CODE REVIEW

**Comment by loicjaouen** [comment]
thanks for answering ;)  how do I do that? if it's me clicking behind the browser, yes, I did, if it is about writing selenium test, no I didn't

**Comment by tobiasschweizer** [comment]
in salsah's sbt console, start salsah, the run `test`

make sure that webapi runs with this flag: `re-start allowResetTriplestoreContentOperationOverHTTP`

**Comment by loicjaouen** [comment]
I see chrome poping up a window, but there's nothing showing up in it, the test procedure gives the result:

```
[info] Run completed in 2 minutes, 9 seconds.
[info] Total number of tests run: 28
[info] Suites: completed 3, aborted 0
[info] Tests: succeeded 5, failed 23, canceled 0, ignored 1, pending 0
[info] *** 23 TESTS FAILED ***
[error] Failed tests:
[error] 	org.knora.salsah.browser.InternationalizationSpec
[error] 	org.knora.salsah.browser.ResourceCreationSpec
[error] 	org.knora.salsah.browser.SearchAndEditSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 131 s, completed 6 avr. 2017 12:27:53
```

and tests complain about: 

```
[info]   org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"id","selector":"simplesearch"}
```

_(the listed element changes according to the test)_

Can we skip that for now and you show me how to properly set-up the selenium test next time we come over?

**Comment by tobiasschweizer** [comment]
Did you unzip the correct chrome drivers? https://github.com/dhlab-basel/Knora/tree/develop/salsah/lib/chromedriver


http://www.knora.org/documentation/manual/rst/salsah/development/build-process.html?highlight=chrome#run-the-automated-tests

**Comment by loicjaouen** [comment]
yes, I followed those guidelines

**Comment by tobiasschweizer** [comment]
Are you sure salsah is running?

```
re-start
test
```

**Comment by tobiasschweizer** [comment]
also run sipi with `local/bin/sipi --config config/sipi.knora-test-config.lua `

**Comment by loicjaouen** [comment]
> Are you sure salsah is running?

I first ran the test after starting salsah but it was doing nothing, then, following the instructions on knora.org, it was not clear that salsah had to run.

Thanks to you, I insisted and for me four test fail (including the first one with a timeout of 1 minute, wrongly diagnosed as "doing nothing").

Thanks for taking the time to test it on your side and for the review.

**Comment by tobiasschweizer** [comment]
strange, the tests passed all for me

I admit that the docs are not very clear, it also happened to us that we did not run salsah before running the tests ...

**Pull request merged**
