### PR TITLE
Allow loading of data (TTL) over HTTP

### LINKED ISSUE #129: Allow loading of test data for salsah tests over HTTP
For tests in `webapi`, we load the test data before executing the automated tests:

```scala
private val storeManager = system.actorOf(Props(new StoreManager with LiveActorMaker), name = STORE_MANAGER_ACTOR_NAME)

    val rdfDataObjects = List(
        RdfDataObject(path = "../knora-ontologies/knora-base.ttl", name = "http://www.knora.org/ontology/knora-base"),
        RdfDataObject(path = "../knora-ontologies/knora-dc.ttl", name = "http://www.knora.org/ontology/dc"),
        RdfDataObject(path = "../knora-ontologies/salsah-gui.ttl", name = "http://www.knora.org/ontology/salsah-gui"),
        RdfDataObject(path = "_test_data/ontologies/incunabula-onto.ttl", name = "http://www.knora.org/ontology/incunabula"),
        RdfDataObject(path = "_test_data/all_data/incunabula-data.ttl", name = "http://www.knora.org/data/incunabula"),
        RdfDataObject(path = "_test_data/ontologies/images-demo-onto.ttl", name = "http://www.knora.org/ontology/images"),
        RdfDataObject(path = "_test_data/demo_data/images-demo-data.ttl", name = "http://www.knora.org/data/images")
    )

...

"Load test data" in {
        storeManager ! ResetTriplestoreContent(rdfDataObjects)
        expectMsg(300.seconds, ResetTriplestoreContentACK())
    }

```

How could we do the same for the tests in Knora `salsah`? One of the problems is that `org.knora.webapi` is not accessible from the project `salsah`.

I just want to load the test data before running the Selenium tests defined in `salsah` because some of them will modify data.

### PR DESCRIPTION
**Pull request by subotic**
### Summary
- Exposes the functionality of the message call ``ResetTriplestoreContent(rdfDataObjects)`` over HTTP
- Added an E2E test spec covering the functionality
- TODO: Need to add documentation !!!
- Refactored the triplestore messages out of the responder messages package
- Refactored the messages package to simplify the naming a bit, e.g.:
  ``messages.v1respondermessages.resourcesmessages`` is now ``messages.v1.responder.resourcesmessages ``. There is still one messages to much (``resourcesmessages`` could be shortened to ``resources``), but I will leave this for another time. Tip: read the package name backwards as if it where a URL.
- Fine-tuning ``.gitignore`` and adding separate ones for ``salsah`` and ``webapi``
- Add chromedriver archives + license
- Add documentation describing startup flags

### Issues
Resolves #129

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
Ok, tell me when it is ready :-) Thx.

**Comment by subotic** [comment]
almost working :)

**Comment by subotic** [comment]
Should work now. You can test it out and see if it also works for you. Ah, also, very important, you need to start the ``webapi`` server with the ``allowResetTriplestoreContentOperationOverHTTP`` flag:

```
(from inside the repository root folder)
$ cd webapi/
$ sbt
> run allowResetTriplestoreContentOperationOverHTTP
```

**Comment by tobiasschweizer** [comment]
We added the request to load the test data as the first test in salsah.

We get the following error:

```
[info] - should load test data *** FAILED *** (493 milliseconds)
[info]   spray.httpx.UnsuccessfulResponseException: Status: 405 Method Not Allowed
[info] Body: HTTP method not allowed, supported methods: OPTIONS
[info]   at spray.httpx.ResponseTransformation$$anonfun$unmarshal$1.apply(ResponseTransformation.scala:39)
[info]   at spray.httpx.ResponseTransformation$$anonfun$unmarshal$1.apply(ResponseTransformation.scala:31)
[info]   at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
[info]   at scala.util.Try$.apply(Try.scala:192)
[info]   at scala.util.Success.map(Try.scala:237)
[info]   at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
[info]   at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
[info]   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
[info]   at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
[info]   at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
[info]   at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
[info]   at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
[info]   at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]   at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]   at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]   at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:10
```

**Comment by tobiasschweizer** [comment]
Wow! This is just great!

Could you please add the missing documentation?

**Comment by subotic** [comment]
yes, I will add the documentation.

> -> the option for webapi so test data are reloaded after a http request

what do you mean by this?

**Comment by tobiasschweizer** [comment]
> run allowResetTriplestoreContentOperationOverHTTP

**Comment by tobiasschweizer** [comment]
file:///home/tobi/gitreps/Knora_github/docs/_build/html/rst/salsah/development/build-process.html#run-the-automated-tests

**Comment by tobiasschweizer** [comment]
once you added the doc, you can merge it

thx.

**Comment by subotic** [comment]
ok, thanks.

Any objections to me adding the cromedriver zip files to ``lib``?

**Comment by benjamingeer** [comment]
You can add ChromeDriver, it's under a BSD licence, you just have to include the copyright notice:

https://groups.google.com/forum/#!searchin/chromedriver-users/license/chromedriver-users/pGbtmW5Nykw/bImZ5MztBgAJ

https://code.google.com/p/chromium/codesearch#chromium/src/LICENSE

**Comment by subotic** [comment]
ok, I've added the chrome driver (including the license) and the missing documentation about the startup flags. I will wait for the automated build to run and if there are no errors, I will merge.

**Pull request merged**
