### PR TITLE
chore(knora): add release notes generation

### PR DESCRIPTION
**Pull request by subotic**

### CODE REVIEW

**Comment by benjamingeer** [comment]
Is it possible to edit the generated release notes? I know I've messed up the merge commit comment for at least one PR merge commit:

https://github.com/dhlab-basel/Knora/commit/df8af5ddfe1c173f23446b38adf3fb13b13d83be

**Comment by subotic** [comment]
sure, just go into the release and edit.

**Comment by subotic** [comment]
thanks for the review 😀

**Comment by subotic** [comment]
This pull request has been mentioned on **Discuss DaSCH**. There might be relevant details there:

https://discuss.dasch.swiss/t/testing-github-linkback/13/3

**Pull request merged**
