### PR TITLE
Add documentation for the incunabula sample project

### PR DESCRIPTION
**Pull request by benjamingeer**
This fills in `docs/rst/introduction/example-project.rst`. It walks the reader through the main points of the `incunabula` ontology, explaining some basic concepts of how to design an ontology for a Knora project.

It also adds some minor fixes and a TODO to `knora-base.tex`.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
Very nice! Just as an idea: Should we provide links to the official documentation in the `rst` (like we do in `knora-base.tex`)? 

When will `knora-base.tex` be integrated in the `rst`-doc?

By the way: How do we solve the definition of default permissions? You mentioned the idea to define them specifically for each user.

**Comment by benjamingeer** [comment]
> Very nice! Just as an idea: Should we provide links to the official documentation in the `rst` (like we do in `knora-base.tex`)?

Which official documentation?

> When will `knora-base.tex` be integrated in the `rst`-doc?

When you make a pull request for that. :)

> By the way: How do we solve the definition of default permissions? You mentioned the idea to define them specifically for each user. 

That's issue #79.

**Comment by tobiasschweizer** [comment]
1. W3C
2. ;-)
3. Ok, got it!

**Comment by benjamingeer** [comment]
For (1), how's this: just a sentence saying that if you want to read the W3C specs, the references are in the Knora base doc.

**Comment by tobiasschweizer** [comment]
Perfect. Merge when you are ready.

**Pull request merged**
