### PR TITLE
Fix reflection error when dump-messages=true in application.conf

### LINKED ISSUE #427: Setting dump-messages = true in application.conf causes Scala reflection error
```
[2017-02-20 16:47:16,744] ERROR - KnoraService(akka://webapi) - Unable to run route http://localhost:3333/v1/projects
scala.ScalaReflectionException: expected a field or an accessor method symbol, you provided object RootJsArrayFormat
       at scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$abort(JavaMirrors.scala:115)
       at scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$ErrorNotField(JavaMirrors.scala:122)
       at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaInstanceMirror.reflectField(JavaMirrors.scala:237)
       at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaInstanceMirror.reflectField(JavaMirrors.scala:233)
       at org.knora.webapi.util.MessageUtil$.$anonfun$toSource$5(MessageUtil.scala:77)
       at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
       at scala.reflect.internal.Scopes$Scope.foreach(Scopes.scala:373)
       at scala.collection.TraversableLike.map(TraversableLike.scala:234)
       at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
       at scala.reflect.internal.Scopes$Scope.map(Scopes.scala:51)
       at org.knora.webapi.util.MessageUtil$.toSource(MessageUtil.scala:74)
       at org.knora.webapi.routing.RouteUtilV1$.$anonfun$runJsonRoute$2(RouteUtilV1.scala:82)
       at scala.util.Success.$anonfun$map$1(Try.scala:251)
       at scala.util.Success.map(Try.scala:209)
       at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
       at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
       at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
       at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
       at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
       at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
       at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
       at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
       at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
       at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
       at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
       at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
       at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
       at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
       at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Thanks to @loicjaouen for reporting.

### PR DESCRIPTION
**Pull request by benjamingeer**
This was implemented in `RouteUtilV1` using `MessageUtil.toSource`, but I can't guarantee that that method can handle any message object, so this changes `RouteUtilV1` to use `toString` instead.

Fixes #427.

### CODE REVIEW

**Comment by benjamingeer** [comment]
@loicjaouen Please let me know if this fixes your error.

**Comment by tobiasschweizer** [comment]
Wouldn't it make more sense to let Loïc review this pull request?

**Comment by benjamingeer** [comment]
I have already asked @loicjaouen for a review. ;-)

**Comment by tobiasschweizer** [comment]
Ah, now it seems correct. I had the impression that I was added in the reviewers section.

**Comment by benjamingeer** [comment]
> I had the impression that I was added in the reviewers section.

You were, I just wanted to give you something to do in case you were bored. :)

**Comment by tobiasschweizer** [comment]
I am the root of boredom. No pull request could change that.

**Comment by loicjaouen** [comment]
I am not sure that I can reproduce it anymore...  
I set the config:
```
    loglevel = "DEBUG"
    stdout-loglevel = "DEBUG"
[...]
 dump-messages = true 
```

but I don't see the `DEBUG` logging in the console or the log file :(

**Comment by benjamingeer** [comment]
I will check...

**Comment by benjamingeer** [comment]
@loicjaouen You need this in `application.xml`:

```
loglevel = "DEBUG"
```

and this in `logback.xml`:

```
<root level="DEBUG">
```

Can you try that and let me know if it works for you? If so, don't forget to approve the changes in this PR so I can merge it (you're the reviewer).

**Comment by loicjaouen** [comment]
perfect, please merge :)

**Comment by benjamingeer** [comment]
You have to "Review changes" and "Approve changes" before I can merge.

**Comment by loicjaouen** [comment]
i'm still learning

**Comment by benjamingeer** [comment]
No problem, thanks :)

**Pull request merged**
