### PR TITLE
feat(admin): Add admin route to dump project data

### LINKED ISSUE #1358: Add admin route to dump project data
Admin route, which returns all data (all ontology graphs, the data graph, project, user, permissions) for a certain project as a trig file.

### PR DESCRIPTION
**Pull request by benjamingeer**
- [x] Add a route, `/admin/projects/iri/<identifier>/AllData`, that returns a [TriG](https://www.w3.org/TR/trig/) file containing a project's ontologies, resource data, admin data, and permissions.
- [x] Add docs.
- [x] Add tests.

Resolves #1358.

### CODE REVIEW

**Comment by benjamingeer** [comment]
It must be Akka setting the file extension, I didn't set it. I'll see if there's a way to specify one.

**Comment by subotic** [comment]
Ah, ok. Thanks :-)

**Comment by benjamingeer** [comment]
It's actually a Safari bug:

https://forums.macrumors.com/threads/safari-erroneously-adding-dms-extension-to-downloads.2080108/

I fixed it by adding a `Content-Disposition` header so the download filename is always `project-data.trig`.

**Comment by subotic** [comment]
Ah cool. But this is an old bug/feature. I know that 15 years ago (give or take) I worked with Lukas on something in PHP and I remember that we had to add something like this (a memorable name for a header). It is time for Apple to fix it.

**Comment by benjamingeer** [comment]
My pleasure, thanks for the review!

**Pull request merged**
