### PR TITLE
assigning a class to the box poping out to create a new entry (linked…

### LINKED ISSUE #413: After an image is uploaded, the field "new entry" doesn't open where expected
I have several resources linked to each others with a `knora-base:hasLinkTo` property.

Those properties work fine (meaning that by selecting it, I am able to open a new window in which a new instance of the linked resource is created) as long as I don't upload an image.

But if I have a resource` rdfs:subClassOf` `knora-base:StillImageRepresentation`, once I uploaded the image, the "new entry" box is not displayed in front of the right property but much higher (which first made me think that it wasn't displayed at all).

capture d ecran 2017-02-08 a 13 53 15

### PR DESCRIPTION
**Pull request by loicjaouen**
… object)

fixes #413

The problem was not the computation of the position of the new box but the origin it was computing from.
When opening the new pop-up window, we missed to assign it with the class attribute `propedit_frame` this the searchbox element search for as its origin position.

So it was related to the previous `propedit_frame` and was not able to shift it position according to the scroll bar of the second pop-up window.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
How would I test this?

**Comment by tobiasschweizer** [comment]
ok, I saw your instructions :-)

**Comment by tobiasschweizer** [comment]
I works for me: I can open several "new entry" fields with te label appearing in the right place.

However, the new windows overly each other.

Can you run the browser tests now?

**Comment by loicjaouen** [comment]
hello Tobias, thanks for the approval.
Regarding your last question; the browser test; the selenium test fails half of the tasks:
```
[info] Run completed in 2 minutes, 22 seconds.
[info] Total number of tests run: 28
[info] Suites: completed 3, aborted 0
[info] Tests: succeeded 14, failed 14, canceled 0, ignored 1, pending 0
[info] *** 14 TESTS FAILED ***
[error] Failed tests:
[error] 	org.knora.salsah.browser.SearchAndEditSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
```

When running the specific task:

```
> testOnly org.knora.salsah.browser.SearchAndEditSpec
```

it looks happy until:

```
[info] - should do a simple search for 'Zeitglöcklein' and open a search result row representing a page (961 milliseconds)
```

and I actually don't have the pictures in sipi... could it be the reason?

**Comment by tobiasschweizer** [comment]
you have to run Sipi with `sipi.knora-test-config.lua`

then it serves always the same image, no matter what you ask for. SO that's the thing to do when you do not have the images locally.

**Comment by loicjaouen** [comment]
thanks :) yes, all tests pass

**Comment by tobiasschweizer** [comment]
:-)

**Pull request merged**
