### PR TITLE
build (travis): fix publish

### PR DESCRIPTION
**Pull request by subotic**

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
I am experiencing problems when compiling: 

```
[info] Compiling 174 Scala sources to /Users/tobi/gitreps/Knora_github/webapi/target/scala-2.12/classes ...
[error] /Users/tobi/gitreps/Knora_github/webapi/src/main/scala/org/knora/webapi/KnoraExceptionHandler.scala:176:17: To compile XML syntax, the scala.xml package must be on the classpath.
[error] Please see https://github.com/scala/scala-xml for details.
[error]                 <html xmlns="http://www.w3.org/1999/xhtml">
[error]                 ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed Nov 29, 2018 7:39:49 AM

```

**Comment by tobiasschweizer** [comment]
I tried `clean` and `reload` in sbt.

**Comment by subotic** [comment]
@tobiasschweizer You need to run SBT from the root of Knora's repository. This should solve the problem. There is now only one build description, i.e. `KnoraBuild.sbt` which is in the root of the repository.

**Comment by subotic** [comment]
@tobiasschweizer could you maybe review this PR?

**Comment by subotic** [comment]
@tobiasschweizer I would also suggest that you close IntelliJ, delete any `.idea` or `.iml` folders/files and open Knora's root directory in IntelliJ. After that, IntelliJ should pick up the new SBT file and do its magic.

**Comment by tobiasschweizer** [comment]
If I run `evicted`:

 Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* org.scala-lang.modules:scala-xml_2.12:1.1.1 is selected over {1.0.6, 1.1.0}
[warn] 	    +- org.knora:webapi_2.12:3.0.0-SNAPSHOT-7-750ab8a0-20181129-1103 (depends on 1.1.1)
[warn] 	    +- com.typesafe.akka:akka-http-xml_2.12:10.1.5 ()     (depends on 1.1.0)
[warn] 	    +- com.typesafe.play:twirl-api_2.12:1.3.13            (depends on 1.0.6)
[warn] 	* com.github.jsonld-java:jsonld-java:0.12.0 is selected over {0.8.3, 0.11.1, 0.10.0}
[warn] 	    +- org.apache.jena:jena-arq:3.4.0                     (depends on 0.10.0)
[warn] 	    +- org.knora:webapi_2.12:3.0.0-SNAPSHOT-7-750ab8a0-20181129-1103 (depends on 0.10.0)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-storage:2.3.2              (depends on 0.8.3)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-client:2.3.2               (depends on 0.8.3)
[warn] 	* com.google.guava:guava:20.0 is selected over 18.0
[warn] 	    +- org.reflections:reflections:0.9.11                 (depends on 20.0)
[warn] 	    +- io.swagger:swagger-core:1.5.18                     (depends on 20.0)
[warn] 	    +- io.swagger:swagger-jaxrs:1.5.18                    (depends on 20.0)
[warn] 	    +- org.elasticsearch:elasticsearch:2.4.6              (depends on 18.0)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-sail-lucene-api:2.3.2      (depends on 18.0)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-http-server-spring:2.3.2   (depends on 18.0)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-sail-model:2.3.2           (depends on 18.0)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-queryalgebra-evaluation:2.3.2 (depends on 18.0)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-storage:2.3.2              (depends on 18.0)
[warn] 	* org.springframework:spring-context:4.3.12.RELEASE is selected over 4.2.1.RELEASE
[warn] 	    +- org.springframework.security:spring-security-core:4.2.5.RELEASE (depends on 4.3.12.RELEASE)
[warn] 	    +- org.springframework:spring-webmvc:4.2.1.RELEASE    (depends on 4.2.1.RELEASE)
[warn] 	    +- org.springframework:spring-web:4.2.1.RELEASE       (depends on 4.2.1.RELEASE)
[warn] 	* org.springframework:spring-expression:4.3.12.RELEASE is selected over 4.2.1.RELEASE
[warn] 	    +- org.springframework.security:spring-security-core:4.2.5.RELEASE (depends on 4.3.12.RELEASE)
[warn] 	    +- org.springframework:spring-context:4.3.12.RELEASE  (depends on 4.3.12.RELEASE)
[warn] 	    +- org.springframework:spring-webmvc:4.2.1.RELEASE    (depends on 4.2.1.RELEASE)
[warn] 	    +- org.springframework:spring-context:4.2.1.RELEASE   (depends on 4.2.1.RELEASE)
[warn] 	* org.springframework:spring-aop:4.3.12.RELEASE is selected over 4.2.1.RELEASE
[warn] 	    +- org.springframework:spring-context:4.3.12.RELEASE  (depends on 4.3.12.RELEASE)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-http-server-spring:2.3.2   (depends on 4.2.1.RELEASE)
[warn] 	    +- org.springframework:spring-web:4.2.1.RELEASE       (depends on 4.2.1.RELEASE)
[warn] 	    +- org.springframework:spring-context:4.2.1.RELEASE   (depends on 4.2.1.RELEASE)
[warn] 	* org.springframework:spring-beans:4.3.12.RELEASE is selected over 4.2.1.RELEASE
[warn] 	    +- org.springframework.security:spring-security-core:4.2.5.RELEASE (depends on 4.3.12.RELEASE)
[warn] 	    +- org.springframework:spring-aop:4.3.12.RELEASE      (depends on 4.3.12.RELEASE)
[warn] 	    +- org.springframework:spring-context:4.3.12.RELEASE  (depends on 4.3.12.RELEASE)
[warn] 	    +- org.springframework:spring-webmvc:4.2.1.RELEASE    (depends on 4.2.1.RELEASE)
[warn] 	    +- org.springframework:spring-web:4.2.1.RELEASE       (depends on 4.2.1.RELEASE)
[warn] 	    +- org.springframework:spring-context:4.2.1.RELEASE   (depends on 4.2.1.RELEASE)
[warn] 	    +- org.springframework:spring-aop:4.2.1.RELEASE       (depends on 4.2.1.RELEASE)
[warn] 	* org.springframework:spring-core:4.3.12.RELEASE is selected over 4.2.1.RELEASE
[warn] 	    +- org.springframework.security:spring-security-core:4.2.5.RELEASE (depends on 4.3.12.RELEASE)
[warn] 	    +- org.springframework:spring-expression:4.3.12.RELEASE (depends on 4.3.12.RELEASE)
[warn] 	    +- org.springframework:spring-beans:4.3.12.RELEASE    (depends on 4.3.12.RELEASE)
[warn] 	    +- org.springframework:spring-aop:4.3.12.RELEASE      (depends on 4.3.12.RELEASE)
[warn] 	    +- org.springframework:spring-context:4.3.12.RELEASE  (depends on 4.3.12.RELEASE)
[warn] 	    +- org.springframework:spring-expression:4.2.1.RELEASE (depends on 4.2.1.RELEASE)
[warn] 	    +- org.springframework:spring-webmvc:4.2.1.RELEASE    (depends on 4.2.1.RELEASE)
[warn] 	    +- org.springframework:spring-web:4.2.1.RELEASE       (depends on 4.2.1.RELEASE)
[warn] 	    +- org.springframework:spring-context:4.2.1.RELEASE   (depends on 4.2.1.RELEASE)
[warn] 	    +- org.springframework:spring-aop:4.2.1.RELEASE       (depends on 4.2.1.RELEASE)
[warn] 	    +- org.springframework:spring-beans:4.2.1.RELEASE     (depends on 4.2.1.RELEASE)
[warn] 	* io.netty:netty:3.10.6.Final is selected over 3.7.0.Final
[warn] 	    +- org.elasticsearch:elasticsearch:2.4.6              (depends on 3.10.6.Final)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-storage:2.3.2              (depends on 3.10.6.Final)
[warn] 	    +- org.apache.zookeeper:zookeeper:3.4.6               (depends on 3.7.0.Final)
[warn] 	* com.spatial4j:spatial4j:0.4.1 is selected over 0.5
[warn] 	    +- org.eclipse.rdf4j:rdf4j-queryalgebra-geosparql:2.3.2 (depends on 0.4.1)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-sail-lucene-api:2.3.2      (depends on 0.4.1)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-storage:2.3.2              (depends on 0.4.1)
[warn] 	    +- org.apache.lucene:lucene-spatial:5.5.4             (depends on 0.5)
[warn] 	* org.apache.lucene:lucene-queryparser:6.4.1 is selected over 5.5.4
[warn] 	    +- org.apache.jena:jena-text:3.4.0                    (depends on 6.4.1)
[warn] 	    +- org.elasticsearch:elasticsearch:2.4.6              (depends on 5.5.4)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-storage:2.3.2              (depends on 5.5.4)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-sail-lucene:2.3.2          (depends on 5.5.4)
[warn] 	* org.apache.lucene:lucene-sandbox:6.4.1 is selected over 5.5.4
[warn] 	    +- org.apache.lucene:lucene-queryparser:6.4.1         (depends on 6.4.1)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-storage:2.3.2              (depends on 5.5.4)
[warn] 	* org.apache.lucene:lucene-queries:6.4.1 is selected over 5.5.4
[warn] 	    +- org.apache.lucene:lucene-queryparser:6.4.1         (depends on 6.4.1)
[warn] 	    +- org.apache.lucene:lucene-highlighter:5.5.4         (depends on 5.5.4)
[warn] 	    +- org.apache.lucene:lucene-suggest:5.5.4             (depends on 5.5.4)
[warn] 	    +- org.elasticsearch:elasticsearch:2.4.6              (depends on 5.5.4)
[warn] 	    +- org.apache.lucene:lucene-grouping:5.5.4            (depends on 5.5.4)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-storage:2.3.2              (depends on 5.5.4)
[warn] 	    +- org.apache.lucene:lucene-spatial:5.5.4             (depends on 5.5.4)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-sail-lucene:2.3.2          (depends on 5.5.4)
[warn] 	* org.apache.lucene:lucene-analyzers-common:6.4.1 is selected over 5.5.4
[warn] 	    +- org.apache.jena:jena-text:3.4.0                    (depends on 6.4.1)
[warn] 	    +- org.apache.lucene:lucene-highlighter:5.5.4         (depends on 5.5.4)
[warn] 	    +- org.apache.lucene:lucene-suggest:5.5.4             (depends on 5.5.4)
[warn] 	    +- org.elasticsearch:elasticsearch:2.4.6              (depends on 5.5.4)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-storage:2.3.2              (depends on 5.5.4)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-sail-lucene:2.3.2          (depends on 5.5.4)
[warn] 	* org.apache.lucene:lucene-core:6.4.1 is selected over 5.5.4
[warn] 	    +- org.apache.lucene:lucene-queryparser:6.4.1         (depends on 6.4.1)
[warn] 	    +- org.apache.jena:jena-text:3.4.0                    (depends on 6.4.1)
[warn] 	    +- org.apache.lucene:lucene-analyzers-common:6.4.1    (depends on 6.4.1)
[warn] 	    +- org.apache.lucene:lucene-highlighter:5.5.4         (depends on 5.5.4)
[warn] 	    +- org.apache.lucene:lucene-suggest:5.5.4             (depends on 5.5.4)
[warn] 	    +- org.elasticsearch:elasticsearch:2.4.6              (depends on 5.5.4)
[warn] 	    +- org.apache.lucene:lucene-grouping:5.5.4            (depends on 5.5.4)
[warn] 	    +- org.apache.lucene:lucene-join:5.5.4                (depends on 5.5.4)
[warn] 	    +- org.apache.lucene:lucene-backward-codecs:5.5.4     (depends on 5.5.4)
[warn] 	    +- org.apache.lucene:lucene-spatial3d:5.5.4           (depends on 5.5.4)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-storage:2.3.2              (depends on 5.5.4)
[warn] 	    +- org.apache.lucene:lucene-spatial:5.5.4             (depends on 5.5.4)
[warn] 	    +- org.eclipse.rdf4j:rdf4j-sail-lucene:2.3.2          (depends on 5.5.4)
[warn] 	    +- org.apache.lucene:lucene-memory:5.5.4              (depends on 5.5.4)
[warn] 	    +- org.apache.lucene:lucene-misc:5.5.4

**Comment by tobiasschweizer** [comment]
> You need to run SBT from the root of Knora's repository. This should solve the problem. There is now only one build description, i.e. KnoraBuild.sbt which is in the root of the repository.

Yes, it works! Thanks a lot!

**Comment by subotic** [comment]
@tobiasschweizer probably. you can remove it.

**Comment by subotic** [comment]
The `evicted` problem we had always. Nothing new.

**Comment by benjamingeer** [comment]
> Do we have to do anything about this?

The only thing we use Selenium for is the SALSAH 1 GUI tests, which work, so I guess we don't need to do anything about that.

**Comment by tobiasschweizer** [comment]
ok, great

**Comment by subotic** [comment]
Thanks for the review. For the future, please keep reviews on point. This PR was about fixing the Travis publish stage (one line of code) and had nothing to do with Salsah, webapi, or SBT build errors. Those should go into a separate issue. We need to start to become more efficient with reviews of PRs. Sometimes they take to long.

**Comment by subotic** [comment]
Yes, we should communicate these things a bit more efficient.

**Comment by tobiasschweizer** [comment]
That would be great!

**Pull request merged**
