### PR TITLE
fix (webapi): update lucene index on sparql update when using graphdb-free

### LINKED ISSUE #629: Lucene indexing
when I import resources as bulk import without specifying graphdb as triplestore in application.conf, import is complete but fulltext search fails. I guess it is due to missing Lucene indexes for imported resources. By specifying graphdb as triplestore in application.conf file and redoing the import, fulltext search works!

Can you please tell me a bit about how configuration of triplestore affects Lucene indexing? shouldn't all imported resources have Lucene Index regardless of triplestore type?

### PR DESCRIPTION
**Pull request by subotic**
### Summary

 - removes any differentiation between `graphdb-se` and `graphdb-free`
 - resolves #629

### CODE REVIEW

**Comment by SepidehAlassi** [comment]
@subotic yes this change solves the issue.

**Comment by subotic** [comment]
great, thanks.

**Comment by subotic** [comment]
@benjamingeer if you maybe could do a quick review. it's not much left since most of the changes are already merged via PR #590.

**Comment by benjamingeer** [comment]
Will do this afternoon.

**Pull request merged**
