### PR TITLE
Remove preview file values

### LINKED ISSUE #1068: Adapt image handling in API v1 to use IIIF for previews
In API v1, two image file values were created for each image: a full-size version and a preview version. This is no longer needed, because Sipi can generate a preview efficiently on the fly in response to a IIIF request.  Therefore, with #1011, image file values created by API v2 will not have `knora-base:isPreview` or `knora-base:qualityLevel`, and there will be only one file value (and one file in Sipi) per image.

The implementation (but not the output) of API v1 therefore needs to be changed so that it no longer uses these predicates. The preview image can be simulated for API v1, so the old SALSAH GUI still works.

Existing data also needs to be converted once v1 is changed. Preferably there will be a conversion routine that handles this.

Then we can remove `isPreview` and `qualityLevel` from `knora-base`.

### PR DESCRIPTION
**Pull request by benjamingeer**
This finishes the work needed for issue #1068. Since PR #1011, preview images in the triplestore and in Sipi are obsolete. This PR removes them and changes `knora-base` accordingly.

- [x] `knora-base.ttl`:
  - [x] Remove everything about preview images.
  - [x] Use `owl:cardinality 1` on `knora-base:hasFileValue` and its subproperties, as per https://github.com/dhlab-basel/Knora/issues/1068#issuecomment-440953742.
- [x] Change API v1 and its Sipi scripts (`convert_from_file.lua` and `convert_from_binaries.lua`) so that they no longer store preview images.
- [x] `upgrade/README.md`: Add a simple convention so Knora release notes can provide scripts and instructions for updating existing data when Knora is upgraded.
  - [x] `upgrade/1230-delete-previews`: Add scripts for updating data for this PR.
  - [x] `upgrade/1211-datetime`: Add a script for updating data for PR #1211.
- [x] Remove preview images in test data (using a transformation added to the `TransformData` utility).
- [x] Update docs and release notes.

Resolves #1068.

### CODE REVIEW

**Comment by benjamingeer** [comment]
@tobiasschweizer Could you please try updating the BEOL data using the scripts in `upgrade/1230-delete-previews`, and let me know if you find any problems?

**Comment by tobiasschweizer** [comment]
@benjamingeer Ok, I will try it. I think I will be able to do that tomorrow.

**Comment by tobiasschweizer** [comment]
I think the Python load test script would also have to be adapted. It is very similar to the import process I am using.

**Comment by benjamingeer** [comment]
> I think the Python load test script would also have to be adapted.

Which script is that?

**Comment by tobiasschweizer** [comment]
> Which script is that?

It is the load test script written in Python. @subotic knows where it is.

**Comment by tobiasschweizer** [comment]
I assume you are getting rid of the non gui case (shared storage of Knora and Sipi) so the import process for StillImageRepresentation has to be adapted.

**Comment by benjamingeer** [comment]
> It is the load test script written in Python.

I didn't know that such a script existed.

> I assume you are getting rid of the non gui case (shared storage of Knora and Sipi) so the import process for StillImageRepresentation has to be adapted.

I haven't done that yet, I'll do it in a later PR.

**Comment by tobiasschweizer** [comment]
> I haven't done that yet, I'll do it in a later PR.

Ah, sorry, I was mistaken then.

**Comment by tobiasschweizer** [comment]
> I didn't know that such a script existed.

We had a stall problem in Knora when doing the import and so we @subotic  a load test script written in Python.

**Comment by subotic** [comment]
The load test can be found here: https://github.com/dhlab-basel/knora-tests

It is the `import-test`.

**Comment by subotic** [comment]
I like the upgrade scripts :-)

**Comment by benjamingeer** [comment]
> I like the upgrade scripts :-)

Thanks, I was hoping you would like them. :)

**Comment by tobiasschweizer** [comment]
> Could you please try updating the BEOL data using the scripts in `upgrade/1230-delete-previews`, and let me know if you find any problems?

I can confirm that `upgrade/1230-delete-previews/delete-preview-values.py` works.

I checked as follows:
1.  I loaded `beol-data.ttl` with preview file values on `develop`
2.  I ran this SPAQRL query: 
```
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
select * 
FROM <http://www.knora.org/data/0801/beol>
where { 
	    
    ?file a knora-base:StillImageFileValue .
    
    FILTER NOT EXISTS {
    	?file knora-base:isPreview true .
    } 
    
} ORDER BY ?file
```
3. I downloaded the result as CSV: ordered list of file value IRIs

4. I switched to `wip/1068-remove-previews`

5. I ran the script `delete-preview-values.py`

5. I ran this SPARQL query: 
```
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
select * 
FROM <http://www.knora.org/data/0801/beol>
where { 
	    
    ?file a knora-base:StillImageFileValue .
    
} ORDER BY ?file
```

6.  I downloaded the result as CSV: ordered list of file value IRIs

7. I did a `diff` on the two CSV: no differences shown

#Questions:

- How would someone convert the data from an existing dump if this branch was already merged back to `develop`? The data would not load because of the consistency checking. Could there be a load script which would not check for consistency just for this case? Then the data could be written to a dump and reloaded with consistency checking.

- In Knora-ui, there is still some logic that deals with marking preview file values when reading them. This would not be necessary anymore. Could you please check with the Knora-ui team if this logic could be removed in a future version of Knora-ui? I think the current Knora-ui should work fine with this PR, the preview marking logic is just not necessary.

**Comment by benjamingeer** [comment]
> I did a `diff` on the two CSV: no differences show

Great, thank you!

> How would someone convert the data from an existing dump if this branch was already merged back to `develop`?

There would be no problem as long as their dump contains the old `knora-base`, which it would if it's a full backup of the repository.

**Comment by benjamingeer** [comment]
@kilchenmann Tobias says:

> In Knora-ui, there is still some logic that deals with marking preview file values when reading them. This would not be necessary anymore. Could you please check with the Knora-ui team if this logic could be removed in a future version of Knora-ui? I think the current Knora-ui should work fine with this PR, the preview marking logic is just not necessary.

**Comment by tobiasschweizer** [comment]
@kilchenmann is on holiday

**Comment by benjamingeer** [comment]
@kilchenmann @flavens Tobias says:

> In Knora-ui, there is still some logic that deals with marking preview file values when reading them. This would not be necessary anymore. Could you please check with the Knora-ui team if this logic could be removed in a future version of Knora-ui? I think the current Knora-ui should work fine with this PR, the preview marking logic is just not necessary.

**Comment by tobiasschweizer** [comment]
@benjamingeer I will redo my Meditationes-import again this afternoon (converted data as basis). If problems occur, I would come back to you. Burt I think it should be fine.

**Comment by benjamingeer** [comment]
@tobiasschweizer OK, thanks very much.

**Comment by tobiasschweizer** [comment]
this is the issue in Knora-ui: https://github.com/dhlab-basel/Knora-ui/issues/190

**Pull request merged**
