### PR TITLE
test (webapi): add lumieres lausanne tests

### LINKED ISSUE #1104: ForbiddenException on v2 resource creation
Hello,
I have this error when I try to create a resource using `http://localhost:3333/v2/resources` API (using Bearer token) while it works with Salsah 1 (I presume using v1 API) :
```
{
    "error": "org.knora.webapi.ForbiddenException: User gilles.faucherand@unil.ch does not have permissions to create a resource in project <http://rdfh.ch/projects/0113>"
}
```
A little bit boring to provide you ontology and so on, could you quick check if there is maybe something wrong with with my following data ? or with create resource v1/v2 API ? :
```json
{
    "@type": "onto:Collection",
    "rdfs:label": "Test",
    "knora-api:attachedToProject": {
        "@id": "http://rdfh.ch/projects/0113"
    },
    "onto:collectionHasTitle": {
        "@type": "knora-api:TextValue",
        "knora-api:valueAsString": "Test"
    },
    "onto:collectionHasUrlElement": {
        "@type": "knora-api:TextValue",
        "knora-api:valueAsString": "test"
    },
    "onto:hasDiffusionType": {
        "@type": "knora-api:BooleanValue",
        "knora-api:booleanValueAsBoolean": false
    },
    "onto:hasOwnerValue": {
        "@type": "knora-api:LinkValue",
        "knora-api:linkValueHasTargetIri": {
            "@id": "http://rdfh.ch/0113/x-I6cMsjSp65NpzPAMytrw"
        }
    },
    "@context": {
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "knora-api": "http://api.knora.org/ontology/knora-api/v2#",
        "onto": "http://0.0.0.0:3333/ontology/0113/lumieres-lausanne/v2#"
    }
}
```

thanks

### PR DESCRIPTION
**Pull request by subotic**
Fixes #1104.

### CODE REVIEW

**Comment by benjamingeer** [comment]
@subotic I added some debugging code to see what permissions the user has. It outputs this:

```
==============================================
Permissions for requestingUser gilles.faucherand@unil.ch:

PermissionsDataADM(
groupsPerProject = Map("http://rdfh.ch/projects/0113" -> Vector(
"http://rdfh.ch/groups/0113/lumieres-lausanne-administrator", 
"http://www.knora.org/ontology/knora-base#ProjectMember"
)), 
administrativePermissionsPerProject = Map("http://rdfh.ch/projects/0113" -> Set(
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#BibliographicNotice"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#NoteRestricted"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#Finding"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#Image"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#Dissemination"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#Contribution"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#Document"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#Position"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#SocietyMembership"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#Note"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#TranscriptionRestricted"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#Transcription"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#DraftPerson"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#AdditionalResourceRestricted"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#News"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#DraftBibliographicNotice"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#Collection"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#Project"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#AdditionalResource"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#User"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#Relationship"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#CollectionRestricted"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#FreeContent"), 
permissionCode = None
), 
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#Person"), 
permissionCode = None
)
))
)
```

**Comment by subotic** [comment]
hmm, the user has the permission:

```
PermissionADM(
name = "ProjectResourceCreateRestrictedPermission", 
additionalInformation = Some("http://www.knora.org/ontology/0113/lumieres-lausanne#User"), 
permissionCode = None
), 
```

**Comment by subotic** [comment]
found the problem:

```
ResourceCreateOperation(http://0.0.0.0:3333/ontology/0113/lumieres-lausanne/v2#User
```

**Comment by subotic** [comment]
The PermissionADM has the knora internal IRI of the resource class, while the V2 responder is querying for the external resource class IRI.

**Comment by benjamingeer** [comment]
🤦 I'm so stupid! Sorry, I'll fix it.

**Comment by subotic** [comment]
thanks :-)

**Pull request merged**
