### PR TITLE
releasing-v1.6.0

### PR DESCRIPTION
**Pull request by subotic**

### CODE REVIEW

**Comment by subotic** [comment]
@benjamingeer should be a quick review :-)

**Comment by subotic** [comment]
thanks :-)

**Comment by subotic** [comment]
ah, crap. need to wait for the tests to pass. we need to make them run faster. the unwritten rule is no longer than 15 minutes. just enough time to get a cup of coffee.

**Comment by benjamingeer** [comment]
I think I've found a computer that's fast enough to run our tests in a reasonable amount of time: https://www.energy.gov/articles/summit-supercomputer-ranked-fastest-computer-world

**Comment by subotic** [comment]
I hope so ;-)

**Pull request merged**
