### PR TITLE
refactor(ontology): Make knora-admin a separate ontology

### LINKED ISSUE #1106: Change knora-admin.ttl to http://www.knora.org/ontology/knora-admin
- Change `knora-admin.ttl` to `http://www.knora.org/ontology/knora-admin`
- Add `KnoraAdmin` object to `OntologyConstants` and move all relevant properties
- Make necessary changes to source-code so that OntologyConstants work again.
- Make necessary changes to test data
- Change groups inside permission strings from `knora-base:GroupName` to `knora-admin:GroupName` in all test data.

Related to #777

### PR DESCRIPTION
**Pull request by benjamingeer**
- [x] Change `knora-admin.ttl` to `http://www.knora.org/ontology/knora-admin`.
- [x] Add `KnoraAdmin` object to `OntologyConstants` and move all relevant properties.
- [x] Make necessary changes to source code so that `OntologyConstants` works again.
- [x] Change groups inside permission strings from `knora-base:GroupName` to `knora-admin:GroupName` in test data.
- [x] Update tests.
- [x] Add upgrade script to update existing repositories.
- [x] Update docs.

Existing repositories must be updated; see `upgrade/1263-knora-admin` for instructions.

Resolves #1106.

### CODE REVIEW

**Comment by subotic** [comment]
cool, thanks 😀

**Comment by tobiasschweizer** [comment]
@benjamingeer Once you have written the update script, could I try it out?

**Comment by benjamingeer** [comment]
@tobiasschweizer 

> Once you have written the update script, could I try it out?

Yes, I was hoping you would. :) I'll let you know when it's ready.

**Comment by benjamingeer** [comment]
@tobiasschweizer You can try the update script now.

**Comment by benjamingeer** [comment]
@subotic The update script needs to know all pairs of `(pred, obj)` where both `pred` and `obj` are in `knora-admin` and can be used together in a triple. Here's the list I made:

```python
# Predicates and objects that can be used together.
pred_obj_pairs = [
    ("forProject", "SystemProject"),
    ("forProject", "DefaultSharedOntologiesProject"),
    ("isInGroup", "UnknownUser"),
    ("isInGroup", "KnownUser"),
    ("isInGroup", "Creator"),
    ("isInGroup", "ProjectMember"),
    ("isInGroup", "ProjectAdmin"),
    ("isInGroup", "SystemAdmin"),
    ("forGroup", "UnknownUser"),
    ("forGroup", "KnownUser"),
    ("forGroup", "Creator"),
    ("forGroup", "ProjectMember"),
    ("forGroup", "ProjectAdmin"),
    ("forGroup", "SystemAdmin")
]
```

Did I miss anything?

**Comment by benjamingeer** [comment]
I realised I could generate that list like this:

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?pred ?obj WHERE {
    GRAPH <http://www.knora.org/ontology/knora-admin> {
        ?pred rdf:type ?predType .
        FILTER(?predType = owl:ObjectProperty || ?predType = owl:DatatypeProperty || ?predType = rdf:Property)
        ?pred knora-base:objectClassConstraint ?predObjectType .
        ?obj rdf:type ?predObjectType .
    }
} ORDER BY ?pred ?obj
```

That gives this list:

```python
pred_obj_pairs = [
    ("belongsToProject", "DefaultSharedOntologiesProject"),
    ("belongsToProject", "SystemProject"),
    ("currentproject", "DefaultSharedOntologiesProject"),
    ("currentproject", "SystemProject"),
    ("forGroup", "Creator"),
    ("forGroup", "KnownUser"),
    ("forGroup", "ProjectAdmin"),
    ("forGroup", "ProjectMember"),
    ("forGroup", "SystemAdmin"),
    ("forGroup", "UnknownUser"),
    ("forProject", "DefaultSharedOntologiesProject"),
    ("forProject", "SystemProject"),
    ("isInGroup", "Creator"),
    ("isInGroup", "KnownUser"),
    ("isInGroup", "ProjectAdmin"),
    ("isInGroup", "ProjectMember"),
    ("isInGroup", "SystemAdmin"),
    ("isInGroup", "UnknownUser"),
    ("isInProject", "DefaultSharedOntologiesProject"),
    ("isInProject", "SystemProject"),
    ("isInProjectAdminGroup", "DefaultSharedOntologiesProject"),
    ("isInProjectAdminGroup", "SystemProject")
]
```

**Comment by tobiasschweizer** [comment]
>  You can try the update script now.

Ok, I will check it. I think I can do it tomorrow.

**Comment by tobiasschweizer** [comment]
I tried to convert my data using the script but got an error (after 1 hour and ten minutes).

GraphDB:

```
[ERROR] 2019-03-27 11:01:33,195 [repositories/knora-test | c.o.t.SailConnectionImpl] Transaction failed. Commit will be rolled back.
com.ontotext.trree.consistency.ConsistencyException: Consistency check max_cardinality_1_without_deletion_flag_1 failed:
http://www.knora.org/ontology/knora-admin#belongsToProject http://www.w3.org/2000/01/rdf-schema#subPropertyOf http://www.knora.org/ontology/knora-base#objectCannotBeMarkedAsDeleted
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject _:genid-feef33931cf84f1e84891858b05c6ace-ub1bL569C28
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-base#SystemProject
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-admin#SystemProject
Consistency check max_cardinality_1_without_deletion_flag_1 failed:
http://www.knora.org/ontology/knora-admin#belongsToProject http://www.w3.org/2000/01/rdf-schema#subPropertyOf http://www.knora.org/ontology/knora-base#objectCannotBeMarkedAsDeleted
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject _:genid-feef33931cf84f1e84891858b05c6ace-ub1bL569C28
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-admin#SystemProject
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-base#SystemProject

	at com.ontotext.trree.consistency.ConsistencyChecker$2.check(ConsistencyChecker.java:107)
	at com.ontotext.trree.SailConnectionImpl.commitInternal(SailConnectionImpl.java:650)
	at com.ontotext.trree.SailConnectionImpl.commit(SailConnectionImpl.java:2263)
	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.commit(SailRepositoryConnection.java:169)
	at com.ontotext.trree.monitorRepository.MonitorRepositoryConnection.commit(MonitorRepositoryConnection.java:202)
	at org.eclipse.rdf4j.repository.base.AbstractRepositoryConnection.conditionalCommit(AbstractRepositoryConnection.java:381)
	at com.ontotext.trree.monitorRepository.MonitorRepositoryConnection.access$400(MonitorRepositoryConnection.java:49)
	at com.ontotext.trree.monitorRepository.MonitorRepositoryConnection$1.execute(MonitorRepositoryConnection.java:349)
	at org.eclipse.rdf4j.http.server.repository.statements.StatementsController.getSparqlUpdateResult(StatementsController.java:281)
	at org.eclipse.rdf4j.http.server.repository.statements.StatementsController.handleRequestInternal(StatementsController.java:122)
	at com.ontotext.graphdb.sesame.StatementsController.handleRequestInternal(StatementsController.java:26)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:881)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.ontotext.forest.core.request.RequestFilter.doFilterInternal(RequestFilter.java:41)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:300)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.ontotext.forest.security.AdminDelegatingFilterProxy.doFilter(AdminDelegatingFilterProxy.java:29)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:501)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
[ERROR] 2019-03-27 11:01:33,287 [repositories/knora-test | o.e.r.h.s.ProtocolExceptionResolver] Error while handling request (500)
org.eclipse.rdf4j.http.server.ServerHTTPException: org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.sail.SailException: com.ontotext.trree.consistency.ConsistencyException: Consistency check max_cardinality_1_without_deletion_flag_1 failed:
http://www.knora.org/ontology/knora-admin#belongsToProject http://www.w3.org/2000/01/rdf-schema#subPropertyOf http://www.knora.org/ontology/knora-base#objectCannotBeMarkedAsDeleted
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject _:genid-feef33931cf84f1e84891858b05c6ace-ub1bL569C28
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-base#SystemProject
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-admin#SystemProject
Consistency check max_cardinality_1_without_deletion_flag_1 failed:
http://www.knora.org/ontology/knora-admin#belongsToProject http://www.w3.org/2000/01/rdf-schema#subPropertyOf http://www.knora.org/ontology/knora-base#objectCannotBeMarkedAsDeleted
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject _:genid-feef33931cf84f1e84891858b05c6ace-ub1bL569C28
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-admin#SystemProject
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-base#SystemProject

	at org.eclipse.rdf4j.http.server.repository.statements.StatementsController.getSparqlUpdateResult(StatementsController.java:307)
	at org.eclipse.rdf4j.http.server.repository.statements.StatementsController.handleRequestInternal(StatementsController.java:122)
	at com.ontotext.graphdb.sesame.StatementsController.handleRequestInternal(StatementsController.java:26)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:881)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.ontotext.forest.core.request.RequestFilter.doFilterInternal(RequestFilter.java:41)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:300)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.ontotext.forest.security.AdminDelegatingFilterProxy.doFilter(AdminDelegatingFilterProxy.java:29)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:501)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.sail.SailException: com.ontotext.trree.consistency.ConsistencyException: Consistency check max_cardinality_1_without_deletion_flag_1 failed:
http://www.knora.org/ontology/knora-admin#belongsToProject http://www.w3.org/2000/01/rdf-schema#subPropertyOf http://www.knora.org/ontology/knora-base#objectCannotBeMarkedAsDeleted
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject _:genid-feef33931cf84f1e84891858b05c6ace-ub1bL569C28
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-base#SystemProject
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-admin#SystemProject
Consistency check max_cardinality_1_without_deletion_flag_1 failed:
http://www.knora.org/ontology/knora-admin#belongsToProject http://www.w3.org/2000/01/rdf-schema#subPropertyOf http://www.knora.org/ontology/knora-base#objectCannotBeMarkedAsDeleted
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject _:genid-feef33931cf84f1e84891858b05c6ace-ub1bL569C28
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-admin#SystemProject
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-base#SystemProject

	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.commit(SailRepositoryConnection.java:172)
	at com.ontotext.trree.monitorRepository.MonitorRepositoryConnection.commit(MonitorRepositoryConnection.java:202)
	at org.eclipse.rdf4j.repository.base.AbstractRepositoryConnection.conditionalCommit(AbstractRepositoryConnection.java:381)
	at com.ontotext.trree.monitorRepository.MonitorRepositoryConnection.access$400(MonitorRepositoryConnection.java:49)
	at com.ontotext.trree.monitorRepository.MonitorRepositoryConnection$1.execute(MonitorRepositoryConnection.java:349)
	at org.eclipse.rdf4j.http.server.repository.statements.StatementsController.getSparqlUpdateResult(StatementsController.java:281)
	... 45 common frames omitted
Caused by: org.eclipse.rdf4j.sail.SailException: com.ontotext.trree.consistency.ConsistencyException: Consistency check max_cardinality_1_without_deletion_flag_1 failed:
http://www.knora.org/ontology/knora-admin#belongsToProject http://www.w3.org/2000/01/rdf-schema#subPropertyOf http://www.knora.org/ontology/knora-base#objectCannotBeMarkedAsDeleted
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject _:genid-feef33931cf84f1e84891858b05c6ace-ub1bL569C28
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-base#SystemProject
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-admin#SystemProject
Consistency check max_cardinality_1_without_deletion_flag_1 failed:
http://www.knora.org/ontology/knora-admin#belongsToProject http://www.w3.org/2000/01/rdf-schema#subPropertyOf http://www.knora.org/ontology/knora-base#objectCannotBeMarkedAsDeleted
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject _:genid-feef33931cf84f1e84891858b05c6ace-ub1bL569C28
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-admin#SystemProject
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-base#SystemProject

	at com.ontotext.trree.SailConnectionImpl.handleTransactionFailure(SailConnectionImpl.java:1104)
	at com.ontotext.trree.SailConnectionImpl.commitInternal(SailConnectionImpl.java:699)
	at com.ontotext.trree.SailConnectionImpl.commit(SailConnectionImpl.java:2263)
	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.commit(SailRepositoryConnection.java:169)
	... 50 common frames omitted
Caused by: com.ontotext.trree.consistency.ConsistencyException: Consistency check max_cardinality_1_without_deletion_flag_1 failed:
http://www.knora.org/ontology/knora-admin#belongsToProject http://www.w3.org/2000/01/rdf-schema#subPropertyOf http://www.knora.org/ontology/knora-base#objectCannotBeMarkedAsDeleted
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject _:genid-feef33931cf84f1e84891858b05c6ace-ub1bL569C28
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-base#SystemProject
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-admin#SystemProject
Consistency check max_cardinality_1_without_deletion_flag_1 failed:
http://www.knora.org/ontology/knora-admin#belongsToProject http://www.w3.org/2000/01/rdf-schema#subPropertyOf http://www.knora.org/ontology/knora-base#objectCannotBeMarkedAsDeleted
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject _:genid-feef33931cf84f1e84891858b05c6ace-ub1bL569C28
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-admin#SystemProject
http://www.knora.org/ontology/knora-base#SystemAdmin http://www.knora.org/ontology/knora-admin#belongsToProject http://www.knora.org/ontology/knora-base#SystemProject

	at com.ontotext.trree.consistency.ConsistencyChecker$2.check(ConsistencyChecker.java:107)
	at com.ontotext.trree.SailConnectionImpl.commitInternal(SailConnectionImpl.java:650)
	... 52 common frames omitted

```

script:

```
Traceback (most recent call last):
  File "./update-knora-admin.py", line 258, in <module>
    main()
  File "./update-knora-admin.py", line 253, in main
    password=password
  File "./update-knora-admin.py", line 210, in do_request
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: http://localhost:7200/repositories/knora-test/statements
```

I can send you a link to my data file if necessary.

**Comment by benjamingeer** [comment]
Hmm, I wonder why I didn't get the same error. Which version of GraphDB are you using?

**Comment by tobiasschweizer** [comment]
still 8.5.0 with a dev license (1 core)

**Comment by tobiasschweizer** [comment]
I sent you the link to my data file (email), could you try to do the conversion and see if it works out?

**Comment by benjamingeer** [comment]
> still 8.5.0 with a dev license (1 core)

I'm using GraphDB 8.8, I wonder if that's why.

> I sent you the link to my data file

The error doesn't seem to have anything to do with your, it's triggered by the `SystemAdmin` group in the `knora-admin` ontology itself.

**Comment by tobiasschweizer** [comment]
> I'm using GraphDB 8.8, I wonder if that's why.

Graphdb 8.5.0 is the version we use in production due to the memory setting problem.

**Comment by benjamingeer** [comment]
I'll try converting `knora-test` with GraphDB 8.5 and see if I can reproduce the error that way.

**Comment by tobiasschweizer** [comment]
> I'll try converting knora-test with GraphDB 8.5 and see if I can reproduce the error that way.

Ok, thanks a lot!

**Comment by tobiasschweizer** [comment]
I have just shared another data file on switchdrive with you (data on BEOL test).

**Comment by benjamingeer** [comment]
@tobiasschweizer I've reproduced the problem with the Knora test data using GraphDB 8.5. I'll try to find a workaround.

**Comment by benjamingeer** [comment]
@tobiasschweizer @subotic I can't get the update to work in SPARQL with GraphDB 8.5. I'm going to take a different approach: dump the contents of the triplestore to files, update the files, then load the files back into the triplestore.

**Comment by tobiasschweizer** [comment]
>  I can't get the update to work in SPARQL with GraphDB 8.5. I'm going to take a different approach: dump the contents of the triplestore to files, update the files, then load the files back into the triplestore.

Do you think you can do it in a way so the two dumps (pre and post update) can be diff-ed?

**Comment by benjamingeer** [comment]
> Do you think you can do it in a way so the two dumps (pre and post update) can be diff-ed?

I think so.

**Comment by tobiasschweizer** [comment]
Great! Then it is easy to verify whether it worked correctly or not.

**Comment by benjamingeer** [comment]
@tobiasschweizer You can try the update script again now. It updates `knora-test` with GraphDB in about 2 minutes. The input and output Turtle files are saved in a temporary directory, and you can look at them, but you can't really diff them, because they're not formatted in quite the same way.

**Comment by tobiasschweizer** [comment]
Ok, I will check it next week

**Comment by benjamingeer** [comment]
@tobiasschweizer Thanks for the review!

**Pull request merged**
