### PR TITLE
Continuous Integration

### LINKED ISSUE #16: Continuous Integration
Move continuous integration to Travis-CI or some other publicly visible platform.

### PR DESCRIPTION
**Pull request by subotic**
Adds configurations necessary to run automatic builds on Travis-CI [1]. For now, the tests are only run with Fuseki.

To see the output, go to [1] and sign in with github.

There was a problem preventing to run SBT builds with forked JVM, but this seems not to be the case anymore.

Resolves #16

[1] https://travis-ci.org

### CODE REVIEW

**Comment by subotic** [comment]
The workaround seems to work.

**Comment by subotic** [comment]
if there are no objections, I will merge this pull request.

**Comment by benjamingeer** [comment]
Let me look at it this morning. :)

**Comment by subotic** [comment]
Thanks :-)

**Comment by benjamingeer** [comment]
This looks fine but could you write a bit of RST documentation about it?

**Comment by subotic** [comment]
Yes, of corse. Completely forgot about this ;-)

**Comment by subotic** [comment]
If it is ok with you, I will merge it :-)

**Comment by benjamingeer** [comment]
Yes, please go ahead and merge.

**Pull request merged**
