### PR TITLE
Improve configuration for more concurrent requests

### LINKED ISSUE #298: Some Sipi-to-Knora connections fail under load
Since the update of Akka some days ago, some of the Sipi round trips to Knora fail when Knora is asking Sipi for a lot of  thumbnails (ca. 400).

The error is caused (or - at least - this is my interpretation) by Knora not answering Sipis request in the `pre_flight` request (defined in `sipi.init-knora.lua`):

```
Request to Knora failed: Error #1175: Connection dropped by peer!
```

Is that a configuration issue? Is the amount of requests Knora will accept from one location limited?

We are trying to replace the round trip anyway, but I think we should investigate.

### PR DESCRIPTION
**Pull request by benjamingeer**
This configures Akka HTTP to handle a large number of concurrent connections, and adds a script to configure the Mac OS X kernel to allow more concurrent connections during testing.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
`man sysctl` on mac os sierra says:

> The -w option has been deprecated and is silently ignored.

**Comment by tobiasschweizer** [comment]
but the output seems to be OK:
```
kern.ipc.somaxconn: 128 -> 12000
net.inet.tcp.msl: 15000 -> 1000
net.inet.ip.portrange.first: 49152 -> 32768
```

**Comment by tobiasschweizer** [comment]
The problem still occurs:

> [2016-12-08 17-23-35] [SIPI:ERROR] Server.http() failed: Error #1391: Couldn't read HTTP header: Connection dropped by peer!
[2016-12-08 17-23-35] [SIPI:ERROR] GET: /knora/5nQDbtsoYV2-EoCxKE3glXm.jpg/full/full/0/default.jpg failed: Unknown error! Unauthorized access!

After running the script the thumbnails were not served at all sometimes.

I experienced his which is new to me:
> [2016-12-08 17-26-25] [SIPI:ERROR] ERROR IN TIFF! Module: ./images/knora/35A8WxFj3qT-ExxBEo12aEr.jpg Error: Not a TIFF or MDI file, bad magic number 55551 (0xd8ff)
[2016-12-08 17-26-25] [SIPI:ERROR] ERROR IN TIFF! Module: ./images/knora/G6H5H4ffEvf-Cy7I2PsyJ2b.jpg Error: Not a TIFF or MDI file, bad magic number 55551 (0xd8ff)
[2016-12-08 17-26-25] [SIPI:ERROR] GET: /knora/35A8WxFj3qT-ExxBEo12aEr.jpg/full/full/0/default.jpg failed: Internal Server Error! SIPI-IMAGE-ERROR at [/Users/tobi/gitreps/Sipi_github/src/SipiImage.cpp: #348]: Could not read file "./images/knora/35A8WxFj3qT-ExxBEo12aEr.jpg"!
[2016-12-08 17-26-25] [SIPI:ERROR] GET: /knora/G6H5H4ffEvf-Cy7I2PsyJ2b.jpg/full/full/0/default.jpg failed: Internal Server Error! SIPI-IMAGE-ERROR at [/Users/tobi/gitreps/Sipi_github/src/SipiImage.cpp: #348]: Could not read file "./images/knora/G6H5H4ffEvf-Cy7I2PsyJ2b.jpg"!

**Comment by benjamingeer** [comment]
In that case I have no idea what's causing #298. Perhaps it's a Sipi bug after all.

**Comment by tobiasschweizer** [comment]
Ok, I think you can merge your changes to `develop` and we have to dig into the issue together with Lukas

**Pull request merged**
