### PR TITLE
fix (webapi): graphdb dbtype settings

### LINKED ISSUE #955: Not able to run latest Knora Version
Dear dhlab,
when I start and compile Knora as described on the README, it gives me the following error ( I only imported ontologies from your repository )

````
reStart
[info] Application webapi not yet started
[info] Starting application webapi in the background ...
webapi Starting org.knora.webapi.Main.main()
webapi[ERROR] objc[87402]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/bin/java (0x10f0db4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1101454e0). One of the two will be used. Which one is undefined.
[success] Total time: 13 s, completed Jul 30, 2018 2:30:13 PM
sbt:webapi> webapi [2018-07-30 14:30:21,904] INFO  - KnoraService(akka://webapi) - KnoraService - applicationStateActorReady
webapi KnoraService - startupTaskRunner starting
webapi [2018-07-30 14:30:24,214] INFO  - KnoraService(akka://webapi) - KnoraService - Startup State: StartingUp
webapi [2018-07-30 14:30:25,022] INFO  - KnoraService(akka://webapi) - KnoraService - Startup State: WaitingForRepository
webapi [2018-07-30 14:30:26,044] INFO  - KnoraService(akka://webapi) - KnoraService - checkRepository - status: NotInitialized: None of the available repositories meet our requirements of id: knora-test, sesameType: owlim:MonitorRepository.
webapi [2018-07-30 14:30:26,045] INFO  - KnoraService(akka://webapi) - Please initialize repository. Will exit now.
webapi[ERROR] Exception in thread "main" akka.pattern.AskTimeoutException: Recipient[Actor[akka://webapi/user/applicationState#-117355951]] had already been terminated. Sender[null] sent the message of type "org.knora.webapi.messages.app.appmessages.GetAppState".
webapi[ERROR] 	at akka.pattern.AskableActorRef$.internalAsk$extension(AskSupport.scala:291)
webapi[ERROR] 	at akka.pattern.AskableActorRef$.$qmark$extension1(AskSupport.scala:283)
webapi[ERROR] 	at org.knora.webapi.KnoraService.startupTaskRunner(KnoraService.scala:225)
webapi[ERROR] 	at org.knora.webapi.KnoraService.startService(KnoraService.scala:185)
webapi[ERROR] 	at org.knora.webapi.KnoraService.startService$(KnoraService.scala:177)
webapi[ERROR] 	at org.knora.webapi.Main$.startService(Main.scala:29)
webapi[ERROR] 	at org.knora.webapi.Main$.delayedEndpoint$org$knora$webapi$Main$1(Main.scala:82)
webapi[ERROR] 	at org.knora.webapi.Main$delayedInit$body.apply(Main.scala:29)
webapi[ERROR] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
webapi[ERROR] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
webapi[ERROR] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
webapi[ERROR] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
webapi[ERROR] 	at scala.collection.immutable.List.foreach(List.scala:389)
webapi[ERROR] 	at scala.App.main(App.scala:76)
webapi[ERROR] 	at scala.App.main$(App.scala:74)
webapi[ERROR] 	at org.knora.webapi.Main$.main(Main.scala:29)
webapi[ERROR] 	at org.knora.webapi.Main.main(Main.scala)
webapi ... finished with exit code 1
````

This happens on Mac and Ubuntu.

Thank you so much for your help.

Best regards,
Jan

### LINKED ISSUE #960: Java options not passed to running tests correctly
There seems to be a problem with `WebapiBuild.sbt` as java options are not passed correctly.

Anything other than `test` and `it` is not working correctly, e.g., `graphdb-se:test` of `graphdb-free:test` is not doing what it should.

### PR DESCRIPTION
**Pull request by subotic**
### Summary

- add distinction between `graphdb-se` and `graphdb-free`
- update `graphdb-free` scripts to include `docker` and `local` variant
- fix and cleanup `WebapiBuild.sbt`

### Issues

- resolves #955 
- resolves #960

### CODE REVIEW

**Comment by janCstoffregen** [comment]
Hi, I used ./graphdb-free-docker-init-knora-test.sh and got the following error:

```
webapi [ERROR] [08/09/2018 17:23:35.096] [webapi-akka.actor.default-dispatcher-10] [akka://webapi/system/pool-master] connection pool for PoolGateway(hcps = HostConnectionPoolSetup(localhost,7200,ConnectionPoolSetup(ConnectionPoolSettings(1024,0,0,2048,2,30 seconds,ClientConnectionSettings(Some(User-Agent: akka-http/10.1.3),10 seconds,Duration.Inf,512,None,WebSocketSettings(<function0>,ping,Duration.Inf,akka.http.impl.settings.WebSocketSettingsImpl$$$Lambda$563/2126537849@16ac6728),List(),ParserSettings(2048,16,1024,64,8192,64,8388608,256,2097152,Strict,RFC6265,true,Set(),Full,Error,Map(If-Range -> 0, If-Modified-Since -> 0, If-Unmodified-Since -> 0, default -> 12, Content-MD5 -> 0, Date -> 0, If-Match -> 0, If-None-Match -> 0, User-Agent -> 32),false,true,akka.util.ConstantFun$$$Lambda$347/546794478@7474d0a9,akka.util.ConstantFun$$$Lambda$347/546794478@7474d0a9,akka.util.ConstantFun$$$Lambda$349/602004810@1946c28),None,TCPTransport),New,1 second),akka.http.scaladsl.HttpConnectionContext$@6466d0d6,akka.event.MarkerLoggingAdapter@1a4a0423))) has shut down unexpectedly
webapi[ERROR] Exception in thread "main" akka.pattern.AskTimeoutException: Recipient[Actor[akka://webapi/user/applicationState#-2103951750]] had already been terminated. Sender[null] sent the message of type "org.knora.webapi.messages.app.appmessages.GetAppState".
webapi[ERROR]   at akka.pattern.AskableActorRef$.internalAsk$extension(AskSupport.scala:291)
webapi[ERROR]   at akka.pattern.AskableActorRef$.$qmark$extension1(AskSupport.scala:283)
webapi[ERROR]   at org.knora.webapi.KnoraService.startupTaskRunner(KnoraService.scala:225)
webapi[ERROR]   at org.knora.webapi.KnoraService.startService(KnoraService.scala:185)
webapi[ERROR]   at org.knora.webapi.KnoraService.startService$(KnoraService.scala:177)
webapi[ERROR]   at org.knora.webapi.Main$.startService(Main.scala:29)
webapi[ERROR]   at org.knora.webapi.Main$.delayedEndpoint$org$knora$webapi$Main$1(Main.scala:82)
webapi[ERROR]   at org.knora.webapi.Main$delayedInit$body.apply(Main.scala:29)
webapi[ERROR]   at scala.Function0.apply$mcV$sp(Function0.scala:34)
webapi[ERROR]   at scala.Function0.apply$mcV$sp$(Function0.scala:34)
webapi[ERROR]   at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
webapi[ERROR]   at scala.App.$anonfun$main$1$adapted(App.scala:76)
webapi[ERROR]   at scala.collection.immutable.List.foreach(List.scala:389)
webapi[ERROR]   at scala.App.main(App.scala:76)
webapi[ERROR]   at scala.App.main$(App.scala:74)
webapi[ERROR]   at org.knora.webapi.Main$.main(Main.scala:29)
webapi[ERROR]   at org.knora.webapi.Main.main(Main.scala)
webapi ... finished with exit code 1

```

Should I use another script or change a setting?

Thank you very much and best regards,
Jan

**Comment by subotic** [comment]
Can you please post the whole log output beginning from `reStart`?

**Comment by janCstoffregen** [comment]
```
sbt:webapi> reStart
[info] Application webapi not yet started
webapi Starting org.knora.webapi.Main.main()
[info] Starting application webapi in the background ...
webapi[ERROR] objc[5584]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/bin/java (0x103f794c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1057f04e0). One of the two will be used. Which one is undefined.
[success] Total time: 7 s, completed Aug 9, 2018 5:39:49 PM
sbt:webapi> webapi [2018-08-09 17:39:58,588] INFO  - KnoraService(akka://webapi) - KnoraService - applicationStateActorReady
webapi KnoraService - startupTaskRunner starting
webapi [2018-08-09 17:40:00,858] INFO  - KnoraService(akka://webapi) - KnoraService - Startup State: StartingUp
webapi [2018-08-09 17:40:01,690] INFO  - KnoraService(akka://webapi) - KnoraService - Startup State: WaitingForRepository
webapi [2018-08-09 17:40:02,720] INFO  - KnoraService(akka://webapi) - KnoraService - checkRepository - status: NotInitialized: None of the available repositories meet our requirements of id: knora-test, sesameType: owlim:MonitorRepository.
webapi [2018-08-09 17:40:02,720] INFO  - KnoraService(akka://webapi) - Please initialize repository. Will exit now.
webapi[ERROR] Exception in thread "main" akka.pattern.AskTimeoutException: Recipient[Actor[akka://webapi/user/applicationState#-1509244296]] had already been terminated. Sender[null] sent the message of type "org.knora.webapi.messages.app.appmessages.GetAppState".
webapi[ERROR]   at akka.pattern.AskableActorRef$.internalAsk$extension(AskSupport.scala:291)
webapi[ERROR]   at akka.pattern.AskableActorRef$.$qmark$extension1(AskSupport.scala:283)
webapi[ERROR]   at org.knora.webapi.KnoraService.startupTaskRunner(KnoraService.scala:225)
webapi[ERROR]   at org.knora.webapi.KnoraService.startService(KnoraService.scala:185)
webapi[ERROR]   at org.knora.webapi.KnoraService.startService$(KnoraService.scala:177)
webapi[ERROR]   at org.knora.webapi.Main$.startService(Main.scala:29)
webapi[ERROR]   at org.knora.webapi.Main$.delayedEndpoint$org$knora$webapi$Main$1(Main.scala:82)
webapi[ERROR]   at org.knora.webapi.Main$delayedInit$body.apply(Main.scala:29)
webapi[ERROR]   at scala.Function0.apply$mcV$sp(Function0.scala:34)
webapi[ERROR]   at scala.Function0.apply$mcV$sp$(Function0.scala:34)
webapi[ERROR]   at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
webapi[ERROR]   at scala.App.$anonfun$main$1$adapted(App.scala:76)
webapi[ERROR]   at scala.collection.immutable.List.foreach(List.scala:389)
webapi[ERROR]   at scala.App.main(App.scala:76)
webapi[ERROR]   at scala.App.main$(App.scala:74)
webapi[ERROR]   at org.knora.webapi.Main$.main(Main.scala:29)
webapi[ERROR]   at org.knora.webapi.Main.main(Main.scala)
webapi ... finished with exit code 1
```

**Comment by subotic** [comment]
ok, I know what the problem is. You need to either change `dbtype` in `application.conf` to `graphdb-free` (default value is `graphdb-se`) or you need start it like this:

```
> set reStart / javaOptions ++= Seq("-Dapp.triplestore.dbtype=graphdb-free")
> reStart
```

**Comment by janCstoffregen** [comment]
ok, I tried it and it works now.

Thank you very much!!!

If I can help with changing the Readme, please let me know ( I don't know if there are more changes to come or not. )
I wonder if the default db should be graphdb-free since this would be for the users who don't have se.

best regards,
Jan

**Comment by janCstoffregen** [comment]
the log output when Knora is running looks very nice now as well!

**Pull request merged**
