### PR TITLE
build (webapi): fix issues that came up during deployment

### LINKED ISSUE #770: Bash missing in alpine based webapi docker image

### LINKED ISSUE #771: Missing aspectjweaver jar in webapi docker image

### PR DESCRIPTION
**Pull request by subotic**
### Summary

- [x] renamed `salsah` folder to `salsah1`
- [x] created `salsah2` folder and added a basic Dockerfile for building `salsah2`. needed in the future for running `salsah2` integration test.
- [x] `salsah1` docker images is now published as `dhlabbasel/salsah1` (was `dhlabbasel/salsah`)
- [x] add `bash` to `webapi` docker image
- [x] add aspectj weaver to stage
- [x] solved graphdb authentication issue. turned out to be a bad configuration.
- [x] on startup, `webapi` tries to query `knora-test` even when `knora-prod` is defined as the repository name. turned out to be a bad configuration.
- [x] update `akka-http` to release (was RC)
- [x] update `akka-base` to latest version as required by `akka-http`
- [x] update `akka-http-circe` to release (was RC)
- [x] fix `graphdb-knora-prod-data.expect`
- [x] add separate internal and external webapi and sipi connection settings
- [x] update release notes

### Issues

- resolves #771
- resolves #770

### CODE REVIEW

**Comment by subotic** [comment]
@benjamingeer should be a fast review. I changed only 3065 files ;-)

**Comment by benjamingeer** [comment]
I didn’t even know we had that many files!

**Comment by subotic** [comment]
I looked at all files. They are all needed. A lot of them are third-party libraries which are checked into the repository.

**Comment by benjamingeer** [comment]
I’m sorry, I was just joking. I will review all 3065 files. :)

**Comment by subotic** [comment]
@benjamingeer ok, now it should be done. BEOL is deployed and works. I'm not touching it anymore :-)

**Comment by subotic** [comment]
thank you very much :-)

**Pull request merged**
