### PR TITLE
fix (ontologies): fix reference for knora-admin

### PR DESCRIPTION
**Pull request by afa-unibas**

### CODE REVIEW

**Comment by afa-unibas** [comment]
just checking if PR's work ;)

**Comment by tobiasschweizer** [comment]
be careful changing the prefix because now all the definitions beginning with `:` belong to `knora-admin`

**Comment by ioolkos** [comment]
ah, yes of course, this is only half the story. 
We need to add the knora-base prefix here, and then prefix every reference accordingly. (exactly like you did in the standoff ontology).

I might add this at some later point...need to do other stuff right now ;)

**Comment by afa-unibas** [comment]
ah, yes of course, this is only half the story.
We need to add the knora-base prefix here, and then prefix every reference accordingly. (exactly like you did in the standoff ontology).

I might add this at some later point...need to do other stuff right now ;)

**Comment by subotic** [comment]
Just a few suggestions: 

 - All tests need to pass
 - Most certainly [OntologyConstants.scala](https://github.com/dhlab-basel/Knora/blob/develop/webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala) will need some changes:
    - ``OntologyConstants.KnoraBase`` -> ``OntologyConstants.KnoraAdmin``
  - also every occurence of these constants throughout our codebase.

**Comment by afa-unibas** [comment]
Did I just open Pandora's box? :) 
but jep, I'll take the assignement.

**Comment by subotic** [comment]
yes :) I have the feeling, that from now on, we are going to have only this kind of assignments. Every time I touch something it proves to be more work than anticipated.

**Comment by afa-unibas** [comment]
@subotic Ivan, can you give me a hint on why travis tests are still failing? is it a certain class of tests failing?

**Comment by subotic** [comment]
@afa-unibas This looks to me like you misspelled something in ``OntologyConstants.scala``. Some property (which needs to be there) could not be found.

**Comment by subotic** [comment]
Also, I don't see any changes to ``admin-data.ttl``, which I would expect.

**Comment by afa-unibas** [comment]
Closing, so that I can sync repos.

**Pull request closed without merging**
