### PR TITLE
feature (search v2): limit fulltext search to standoff class

### PR DESCRIPTION
**Pull request by tobiasschweizer**
This PR replaces https://github.com/dhlab-basel/Knora/pull/826 (the branch `wip/standoff_search` still has to be deleted once this PR is merged).

This PR provides the possibility to restrict a fulltext search to a standoff class.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@benjamingeer I had to reapply the changes to a new branch because I got a lot of merge conflicts. The previous branch was based on the standoff PR that has been merged. This looked good when I changed the base branch to develop. Bt then I got a lot of merge conflicts in files that I haven't changed in the PR itself, but for the standoff PR.

**Comment by tobiasschweizer** [comment]
Ah, I should add the new param to the docs!

**Comment by benjamingeer** [comment]
> Am I right to assume that it makes no difference whether the user submits Iri params in complex or simple schema since they are converted to the internal one anyway?

I think so, but try it and see. Also, if we do what we talked about in #813, I think we should remove standoff completely from the simple schema. So then we shouldn't allow standoff class IRIs in the simple schema in requests.

**Comment by tobiasschweizer** [comment]
I tried it, it makes no difference at all. The response format has to be chosen either via the header or the "schema" param. 

So I can mere this PR?

**Comment by benjamingeer** [comment]
OK, just merge it then.

**Comment by tobiasschweizer** [comment]
Ok, thx!

**Comment by mattssp** [comment]
Hi @tobiasschweizer @benjamingeer , if I should want to search for a knora-resource that is referenced by a standoffLinkTag that contains a search phrase, would that be possible with KNARL (even if you remove standoff from the simple schema)? Or would it be useful to implement this as a feature in knora?

**Comment by tobiasschweizer** [comment]
@mattssp This is a closed PR, could you please comment here #630 instead?

Maybe #813 helps here: we plan to add support for the complex schema in KnarQL, so one could search for standoff.

**Pull request merged**
