### PR TITLE
fixing image rotation, ref: #726

### PR DESCRIPTION
**Pull request by loicjaouen**
fixes: #726

### CODE REVIEW

**Comment by loicjaouen** [comment]
it is not ready for review because:
- it crashes the build for reasons that I did not investigated yet
- i was head down on project import last week and didn't follow up the many changes that happened on the project and updating it for committing the code broke my local environment

Guys... that was not the right week to look elsewhere you did an amazing amount of work ;)

**Comment by loicjaouen** [comment]
so now it looks like:

capture d ecran 2018-03-09 a 19 35 31

**Comment by loicjaouen** [comment]
but it still misses this:

capture d ecran 2018-03-09 a 19 01 49

**Comment by loicjaouen** [comment]
now it looks like:

capture d ecran 2018-03-10 a 00 49 21

**Comment by benjamingeer** [comment]
Moved to #817.

**Pull request closed without merging**
