### PR TITLE
feat(api-v2): Allow a resource to be created as a specified user

### LINKED ISSUE #1280: Set attachedToUser on resource creation
It will be very helpful for us to set the attached user IRI on resource creation (like creation/modif dates etc.).

The only solution I see is to login with the concerned user, create resource, logout. In a database migration scenario it is no really efficient.

Related to #1217

### PR DESCRIPTION
**Pull request by benjamingeer**
Resolves #1280.

### CODE REVIEW

**Comment by benjamingeer** [comment]
@gfoo Please try this and see if it does what you need.

**Comment by gfoo** [comment]
Won't have time right now, on holydays for the next week, back on April 24th. I will test at that time.

**Comment by benjamingeer** [comment]
@gfoo OK, bonnes vacances!

**Comment by benjamingeer** [comment]
Thank you!

**Pull request merged**
