### PR TITLE
update drawings-gods files

### PR DESCRIPTION
**Pull request by mrivoal**
This PR is related to issue #492

### CODE REVIEW

**Comment by benjamingeer** [comment]
A Travis test fails on this branch:

```

[info] - should allow drawings-gods-test-ddd1 user to see newly created resource and all properties *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: expected class org.knora.webapi.messages.v1.responder.resourcemessages.ResourceCreateResponseV1, found class akka.actor.Status$Failure (Failure(org.knora.webapi.OntologyConstraintException: Values were not submitted for the following property or properties, which are required by resource class http://www.knora.org/ontology/drawings-gods#Person: http://www.knora.org/ontology/drawings-gods#hasPersonGender, http://www.knora.org/ontology/drawings-gods#hasDrawingChildTotal))
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:473)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:454)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:454)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:814)
[info]   at org.knora.webapi.other.v1.DrawingsGodsV1Spec.$anonfun$new$9(DrawingsGodsV1Spec.scala:148)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

**Comment by benjamingeer** [comment]
This seems to be the cause:

```
Values were not submitted for the following property or properties, which are required by resource class http://www.knora.org/ontology/drawings-gods#Person: http://www.knora.org/ontology/drawings-gods#hasPersonGender, http://www.knora.org/ontology/drawings-gods#hasDrawingChildTotal
```

**Comment by benjamingeer** [comment]
So it looks like `DrawingsGodsV1Spec` needs to be updated considering that `drawings-gods:hasPersonGender` and `drawings-gods:hasDrawingChildTotal` are now required properties in `drawings-gods:Person`.

**Comment by mrivoal** [comment]
I am not sure of what has to be done here. My PR was linked to issue #492 (I was only trying to share some files with you), but I think @loicjaouen's PR in #503 fixes it. 

I will check with @loicjaouen tomorrow and let you know.

**Comment by mrivoal** [comment]
Since issue #492 is fixed, I don't need to update drawings-gods files. It is not a stable ontology yet. 

So, just forget it.

**Pull request closed without merging**
