### PR TITLE
Fix image orientation in SALSAH 1 (moved from #768)

### PR DESCRIPTION
**Pull request by benjamingeer**
This is PR #768, adapted for the current `develop`.

The Knora-Sipi integration tests pass.

@loicjaouen Can you check that this does what you want? If so, I think we can merge it.

fixes: #726

### CODE REVIEW

**Comment by loicjaouen** [comment]
Thanks for caring @benjamingeer , yes, that's the code change that I wanted, if the tests pass, let's move forward.

**Comment by benjamingeer** [comment]
You're welcome! It's always great to get bug fixes. :) Could you just update the release notes? I forgot to do that.

**Comment by loicjaouen** [comment]
> Could you just update the release notes?

oups, sorry @benjamingeer , I am catching up too late

**Comment by benjamingeer** [comment]
No worries. :)

**Pull request merged**
