### PR TITLE
fix (extended search date LT_EQ GT_EQ): fix wrong conditions for date comparison

### PR DESCRIPTION
**Pull request by tobiasschweizer**
The conditions for LT_EQ and GT_EQ were wrong. Logically, they are simply the negations of GT and LT, respectively.

closes  https://github.com/dhlab-basel/Knora/issues/575

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
should fix https://github.com/dhlab-basel/Knora/issues/575

**Comment by aeneaskaiser** [comment]
I can verify that the changes to `searchExtendedGraphDB.scala.txt `and `searchExtendedStandard.scala.txt` produce logically consistent search results, so that the sets of results for LT and GT_EQ form a partition of the whole set of date values, and also the sets of results for GT and LT_EQ form a partition of the whole set of date values.
This seems to be a desirable property of the semantics of the comparison operators on date values to me. Especially since the previous semantics would have left some date values unfindable by combining searches for e.g. LT and GT_EQ.

However now the documentation for LT_EQ and GT_EQ in `docs/rst/knora-api-server/api_v1/reading-and-searching-resources.rst` is out of date. It still describes the behaviour prior to this PR. Maybe this should be updated in the same PR?

**Comment by aeneaskaiser** [comment]
As for the changes introduced in `SearchRouteV1.scala` i can verify that no new bugs were introduced, since only error messages were changed. But to judge if the semantics of the error messages make sense, and to judge if this change closes/answers issue #575, i feel i don’t know the Knora code base well enough. Care to ask someone else for a review? Or maybe we could look at the context of the changes together?

**Comment by tobiasschweizer** [comment]
> However now the documentation for LT_EQ and GT_EQ in docs/rst/knora-api-server/api_v1/reading-and-searching-resources.rst is out of date. It still describes the behaviour prior to this PR. Maybe this should be updated in the same PR?

Absolutely! I will do it right away!

> But to judge if the semantics of the error messages make sense, and to judge if this change closes/answers issue #575, i feel i don’t know the Knora code base well enough.

The error messages just indicate that a URL GET parameter's value is not a valid Iri (although it should be).  I added a comment about correct URL encoding because we had a case where a library URL encoded an already URL encoded string (so then it was URL encoded twice and hence the Iri validation failed).

**Pull request merged**
