### PR TITLE
Wip/sbt assembly merge

### LINKED ISSUE #440: webapi sbt assembly is broken
it complains about duplicate files not knowing which one to choose.

the main sources of them are:
- `org/aopalliance`: `aopalliance` against `spring-aop` 
- `org/apache/commons/logging`: `jcl-over-slf4j` against `commons-logging`

I see this only since #421 :( where I added a `spring` dependency.

I guess being able to `assemble` the fat jar should be part of the tests?

### PR DESCRIPTION
**Pull request by loicjaouen**
to fix #440 

Take the first version of the `org.aopallience` class files included by the `aopalliance` but also provided by `spring`.

I don't understand which version is chosen between the two, **first**, is it consistent?  
I would have prefered to use the `% "provided"` tag in the `libraryDependencies`, but spring brings more than aop and I could not find where aop is included otherwise.

### CODE REVIEW

**Comment by subotic** [comment]
Do we actually need ``sbt-assembly``? I added it with the idea to use it for deployment. Now I'm using  [SBT Native Packager](https://github.com/sbt/sbt-native-packager) which creates a nice distribution.

If you are interested, you can take a look at #360. The command for using it is ``sbt stage``.

**Comment by loicjaouen** [comment]
whatever works ;)

right now I am following your instructions from:  
https://www.maillist.unibas.ch/pipermail/knora-user/2016-July/000077.html

I will have a look at stage and revert

**Comment by loicjaouen** [comment]
allright; I didn't see it because it is a PR
Cool: you did the clean-up there, removing the `assembly` build task, so we stop using it and avoid confusion.

But it is still a work-in-progress, isn't it?  
(right now the jar produced throws an error when tried with `java -jar`)

**Comment by subotic** [comment]
Actually, it should work. These are the steps:

```
 $ sbt stage
 $ cd ./target/universal/stage
 $ ./bin/webapi
```

**Comment by loicjaouen** [comment]
Allright; yes it works.

I still have two questions:

- status of this PR: shall I release on `develop` or on `wip/knora_deployment_packaging`?  
If the answer is `develop`, then we should push this PR, even if it is short-lived.

- how do you recommend to release? We don't have a fat jar any more but a collection of jars and an init script to put them all in the class path. I guess it doesn't make sense to zip and ship the `stage` directory, does it? Do you checkout and build in the Docker container?
 
Background: we are in fast release mode on 3 set-ups that we maintain; `test`, `demo` and `prod`.

**Comment by subotic** [comment]
> status of this PR: shall I release on develop or on wip/knora_deployment_packaging?
If the answer is develop, then we should push this PR, even if it is short-lived.

I would say ``develop``. I didn't push this PR, because I simply checkout this branch.

> how do you recommend to release? We don't have a fat jar any more but a collection of jars and an init script to put them all in the class path. I guess it doesn't make sense to zip and ship the stage directory, does it? Do you checkout and build in the Docker container?

I build directly inside docker. I will add you to the repository I'm working on in Gitlab. Then you can take a look at the Dockerfiles. Basically, this is my Dockerfile for building ``webapi``:

```
FROM dhlabbasel/webapi-base:latest
MAINTAINER Ivan Subotic "ivan.subotic@unibas.ch"
# Get Knora, build webapi release package, cleenup
RUN \
  git clone -b wip/knora_deployment_packaging --single-branch --depth=1 https://github.com/dhlab-basel/Knora.git /knora && \
  cd /knora/webapi && \
  sbt stage && \
  mkdir /webapi && \
  cp -r /knora/webapi/target/universal/stage/* /webapi && \
  rm -rf /knora
# Add custom configurations for our environment
COPY ./conf/* /localdata/webapi/
# Expose the webapi default port
EXPOSE 3333
CMD (echo 'need to run with custom command')
```

**Comment by subotic** [comment]
@loicjaouen  Can I delete this pull-request?

**Comment by loicjaouen** [comment]
sure, sorry, I didn't switch to the `sbt stage` way yet, but we can close this one here.

**Pull request closed without merging**
