### PR TITLE
adding project specific icons

### PR DESCRIPTION
**Pull request by loicjaouen**
Adding project Lumières.Lausanne icons

### CODE REVIEW

**Comment by benjamingeer** [comment]
The abbreviation `ll` is confusing because it looks like the number eleven. Could you use `LL` instead?

**Comment by benjamingeer** [comment]
Or better yet, `lumières-lausanne`?

**Comment by loicjaouen** [comment]
Why not... let's live in the 21rst century and put accentuated letters in file names and IRIs.
The official name for the project is _Lumières.Lausanne_, being an IT guy from the previous century, it looks a bit strange to have file names like:
`.../salsah/src/public/project-icons/Lumières.Lausanne/auth_user.jpg`
and turtle like:
```
@prefix Lumières.Lausanne: <http://www.knora.org/ontology/Lumières.Lausanne#> .
<http://data.knora.org/0f89e039230502> rdf:type Lumières.Lausanne:Documentfile ;
```

But I guess it is only lack of practice.

Do you see any inconvenience to use _Lumière.Lausanne_ ?

**Comment by benjamingeer** [comment]
Knora uses UTF-8 for everything, and both Linux and Mac OS X support UTF-8 filenames, so I see no problem.

**Comment by benjamingeer** [comment]
Great, thanks, please go ahead and merge.

**Comment by loicjaouen** [comment]
I have no rights on the project :)

**Comment by benjamingeer** [comment]
Sorry, sent you an invite, now you should be able to merge.

**Comment by loicjaouen** [comment]
thanks Ben!

**Pull request merged**
