### PR TITLE
Use Apache HTTP client

### LINKED ISSUE #1081: Bulk import error after a webapi docker restart
(Using docker compose dev)

When I update an ontology, I relaunch the bootstrap script `./graphdb-se-docker-init-knora-test.sh` and then restart the webapi container `docker-compose restart  webapi`.

Then I have this error when I launch the first bulk import:
`{"status":11,"error":"org.knora.webapi.BadRequestException: An error occurred when requesting mapping http://rdfh.ch/standoff/mappings/StandardMapping: Failed to connect to triplestore"}`

then everything works fine for the next bulk imports.

### LINKED ISSUE #1122: Triplestore connection error when using dockerComposeUp
I can run the bulk import in #1100 without errors if I:

- use `webapi/reStart` to start Knora
- use GraphDB's `bin/graphdb` script to start GraphDB
- run Sipi in Docker

But if I start everything with `dockerComposeUp` in SBT, and then run the bulk import script, I get this error in the client:

```
{
  "status":11,
  "error":"org.knora.webapi.BadRequestException: An error occurred when requesting mapping http://rdfh.ch/standoff/mappings/StandardMapping: Failed to connect to triplestore"
}
```

and this error in the server log:

```
webapi_1_f5153ef8fb2c | [2018-12-10 14:26:17,775] ERROR - OneForOneStrategy - Failed to connect to triplestore
webapi_1_f5153ef8fb2c | org.knora.webapi.TriplestoreConnectionException: Failed to connect to triplestore
webapi_1_f5153ef8fb2c | 	at org.knora.webapi.TriplestoreConnectionException$.apply(Exceptions.scala:249)
webapi_1_f5153ef8fb2c | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$1.applyOrElse(HttpTriplestoreConnector.scala:644)
webapi_1_f5153ef8fb2c | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$1.applyOrElse(HttpTriplestoreConnector.scala:642)
webapi_1_f5153ef8fb2c | 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
webapi_1_f5153ef8fb2c | 	at scala.util.Failure.recover(Try.scala:230)
webapi_1_f5153ef8fb2c | 	at scala.concurrent.Future.$anonfun$recover$1(Future.scala:392)
webapi_1_f5153ef8fb2c | 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
webapi_1_f5153ef8fb2c | 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
webapi_1_f5153ef8fb2c | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
webapi_1_f5153ef8fb2c | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
webapi_1_f5153ef8fb2c | 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
webapi_1_f5153ef8fb2c | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
webapi_1_f5153ef8fb2c | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
webapi_1_f5153ef8fb2c | 	at java.base/java.lang.Thread.run(Thread.java:844)
webapi_1_f5153ef8fb2c | Caused by: java.lang.IllegalStateException: Substream Source cannot be materialized more than once
webapi_1_f5153ef8fb2c | 	at akka.stream.impl.fusing.SubSource$$anon$4.setCB(StreamOfStreams.scala:756)
webapi_1_f5153ef8fb2c | 	at akka.stream.impl.fusing.SubSource$$anon$4.preStart(StreamOfStreams.scala:766)
webapi_1_f5153ef8fb2c | 	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:295)
webapi_1_f5153ef8fb2c | 	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:557)
webapi_1_f5153ef8fb2c | 	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:679)
webapi_1_f5153ef8fb2c | 	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:727)
webapi_1_f5153ef8fb2c | 	at akka.actor.Actor.aroundPreStart(Actor.scala:528)
webapi_1_f5153ef8fb2c | 	at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
webapi_1_f5153ef8fb2c | 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:670)
webapi_1_f5153ef8fb2c | 	at akka.actor.ActorCell.create(ActorCell.scala:652)
webapi_1_f5153ef8fb2c | 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
webapi_1_f5153ef8fb2c | 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

However, other API requests (e.g. http://localhost:3333/admin/lists) seem to work.

In my Docker preferences (on macOS), Docker has 4 CPUs and 6 GB of memory.

### PR DESCRIPTION
**Pull request by benjamingeer**
This PR changes `HttpTriplestoreConnector`, `SipiResponderV1`, and `SipiResponderV2` to use [Apache HttpClient](http://hc.apache.org/httpcomponents-client-ga/) instead of the Akka HTTP client API.

The aim of this PR is to reduce the amount of time we have to spend on HTTP client issues. We've had a series of time-consuming issues involving difficult-to-explain Akka HTTP exceptions, including:

- `akka.http.impl.engine.client.OutgoingConnectionBlueprint$UnexpectedConnectionClosureException`: #741
- `java.lang.IllegalStateException: Substream Source cannot be materialized more than once`: #1122 

There's also the problem of freezing on macOS: https://github.com/akka/akka/issues/25605.

Akka HTTP is a relatively new project, while Apache HttpClient is nearly 20 years old and still actively developed. Its API also seems simpler and easier to understand. And I think we don't use or need most of the features of the Akka HTTP client API.

Fixes #1122.
Fixes #1081.

### CODE REVIEW

**Comment by benjamingeer** [comment]
@gfoo Could you please try this branch and see if it fixes #1081 for you?

**Comment by gfoo** [comment]
yes, it works. Notice that I use: `gdbImage := "dhlabbasel/graphdb-free:8.3.1"`.

**Comment by subotic** [comment]
I don't think that `GraphDB 8.3.1` is supported anymore. There are some queries, that require `GraphDB 8.5.0`.

**Comment by subotic** [comment]
I've sent you all a license. GraphDB-Free is resource intensive and slow.

**Comment by subotic** [comment]
We tried it on Travis, and could never get it to work. Always had some timeouts. If you have a fast CPU and not a lot of data, then it will maybe work.

**Comment by gfoo** [comment]
```
Nom du modèle :	MacBook Pro
  Identifiant du modèle :	MacBookPro11,4
  Nom du processeur :	Intel Core i7
  Vitesse du processeur :	2,5 GHz
  Nombre de processeurs :	1
  Nombre total de cœurs :	4
  Cache de niveau 2 (par cœur) :	256 Ko
  Cache de niveau 3 :	6 Mo
  Mémoire :	16 Go
```
Conf Docker: 
```
CPU 6
Mem 8 Go
```

> GraphDB-Free is resource intensive and slow.

ah ok, maybe it explains my noisy fan so often!

Anyway I now use your license, thanks for that.

**Comment by benjamingeer** [comment]
@subotic Which GraphDB SE version should we be using now?

**Comment by subotic** [comment]
> @subotic Which GraphDB SE version should we be using now?

8.5.0: https://github.com/dhlab-basel/Knora/blob/develop/project/Dependencies.scala

If you run docker-compose from SBT, then this is already set correctly.

There are some memory issues with later versions, which we are still working on.

**Comment by benjamingeer** [comment]
> We should run the load-tests to be sure.

Thanks, I‘ll do it tomorrow.

**Comment by subotic** [comment]
Just to have it on record. I find this at most a temporary fix. The problem is not Akka HTTP, it is more likely that the way we are using Akka and Akka HTTP is producing the problem. Just exchanging one technology with another because we don't understand it, is not really the solution. Now we have Akka, Akka HTTP, and Apache HTTP. Our library dependency tree has yet again considerably. We are going to pay the price at some other point.

Next year we should try to find a solution to the real problem.

**Comment by benjamingeer** [comment]
> The problem is not Akka HTTP

Perhaps. But all software has bugs. And newer software with a very innovative design is perhaps likely to have more bugs than older software with a more conventional design. When we first tried Akka HTTP, it had a memory leak, which I reported to them, and they confirmed and fixed it. And they thanked me for the bug report: https://github.com/akka/akka/issues/16900#issuecomment-92844257

It actually seems to me that we use very few features of Akka in general, and perhaps we don't really need it at all. But let's talk about this next year.

**Comment by benjamingeer** [comment]
The load test completed without errors.

**Pull request merged**
