### PR TITLE
fix (V2 date) : return era of date

### PR DESCRIPTION
**Pull request by SepidehAlassi**
is related to https://github.com/dhlab-basel/Salsah/pull/154

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@SepidehAlassi We have to adapt the test data :-)

- ontology route since we added new properties
- e2e tests that involve dates

**Comment by tobiasschweizer** [comment]
@benjamingeer We added support for the indication of the era in the V2 route. Could you please check if this correct with the knora-api ontology (complex)?

**Comment by tobiasschweizer** [comment]
holy shit, I have just discovered this for date in the simple ontology:

```
"owl:withRestrictions": {
"xsd:pattern": "(GREGORIAN|JULIAN):\\d{1,4}(-\\d{1,2}(-\\d{1,2})?)?( BC| AD| BCE| CE)?(:\\d{1,4}(-\\d{1,2}(-\\d{1,2})?)?( BC| AD| BCE| CE)?)?"
}
```

**Comment by tobiasschweizer** [comment]
pretty impressive :-)

**Comment by benjamingeer** [comment]
This PR looks good to me!

> I have just discovered this for date in the simple ontology

I think it has no effect on anything, but it looks nice. :)

**Comment by tobiasschweizer** [comment]
> I think it has no effect on anything, but it looks nice. :)

I guess someone will develop a client that actually validates the data being served from Knora.

**Pull request merged**
