### PR TITLE
Wipi/generate IIIF urls

### PR DESCRIPTION
**Pull request by tobiasschweizer**
Now, true IIIF URLs are generated

What needs to be changed in the future, is that we do not include the filename in the URL but the file value IRI (we need to pass the file value Iri to the function from resources responder)

Sipi will then ask Knora about the permissions and the filename for a given file value Iri.

### CODE REVIEW

**Comment by benjamingeer** [comment]
Can you please change the search responder so it uses these URLs, too?

According to #63, we're not adding `.sbtrc` to the repository. If you did this by mistake, you could add it to `.gitignore` instead.

**Comment by tobiasschweizer** [comment]
Ok, I added the handling for previews returned by the search responder

I have already added `.sbtrc` to git `.gitignore` on this branch

**Comment by tobiasschweizer** [comment]
This si still open: https://github.com/dhlab-basel/Knora/issues/45

**Comment by benjamingeer** [comment]
Sorry, my mistake about `.sbtrc`.

OK, looks good to merge.

**Comment by tobiasschweizer** [comment]
Currently the search only looks for stillimagerepresentations, but maybe also a movie could have a preview, e.g a single frame.

**Comment by tobiasschweizer** [comment]
I created issues #74 and #73 so I do not forget :-)

**Pull request merged**
