### PR TITLE
Fix Browser Tests for Salsah1

### LINKED ISSUE #847: SALSAH1 Browser Tests fail
On  `develop`, the Salsah1 browser tests fail. I remember that they used to work some weeks ago.

Could we have a look at them?

### PR DESCRIPTION
**Pull request by tobiasschweizer**
Fixes failing tests in automated tests for Salsah1. Adds more instructions how run the automated browser tests for Salsah 1.

replaces #831 

closes #847

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@subotic @benjamingeer The SALSAH browser tests are fixed now :-) I think the problem were just some changes in GUI order and Selenium got confused (xpath expressions were broken).

**Comment by benjamingeer** [comment]
Yay :)

**Comment by tobiasschweizer** [comment]
@subotic Could you run the tests :-)?

**Comment by tobiasschweizer** [comment]
@subotic Do the browser tests work for you?

**Comment by subotic** [comment]
yes, just finished running them.

**Comment by tobiasschweizer** [comment]
@subotic Very nice!

For some reason, travis cannot build the docs ...

**Comment by subotic** [comment]
I will take a look at building the docs. This is very annoying. It happens every few days.

**Comment by tobiasschweizer** [comment]
@subotic Thanks. Can merge this once the tests have passed?

**Comment by subotic** [comment]
yes, thanks :-)

**Pull request merged**
