### PR TITLE
fix(sipi): Don't try to read a file value in a deleted resource

### LINKED ISSUE #1328: Incorrect error handling when a value in a deleted resource is requested
I am not sure if it is very dangerous but our log fills up with:
```
api_1_e9a49bba8d18 | org.knora.webapi.InconsistentTriplestoreDataException: entity http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA has no project
```

I am not sure of the meaning of "has no project" but it is a `Value` and values have no `knora-base:attachedToProject`.

Is it something to worry about?

If not, is it hard to remove from the logs?

### PR DESCRIPTION
**Pull request by benjamingeer**
- [x] If Sipi requests information from Knora about a file in a deleted resource, return 404 Not Found.
- [x] Remove some obsolete things that should have been removed before.

Fixes #1328.

### CODE REVIEW

**Comment by subotic** [comment]
Hmm, so when the file value is deleted, what happens to the image in sipi? We cannot delete the image in sipi, because if someone wants a past version of the resource where the file value was not deleted, then the image should be servable, right? Shouldn't then the `admin/files` route return `resource deleted` or something of sorts? There is no status code for this, unfortunately.

Ahh, a deleted resource. If we request the resource from a time before deletion, then the same question arises, right?

**Comment by benjamingeer** [comment]
> We cannot delete the image in sipi, because if someone wants a past version of the resource where the file value was not deleted, then the image should be servable, right?

Yes. Deleting a value is considered a change in the resource (like deleting a word in a text file, or the contents of a cell in a spreadsheet), so you can request the resource as it was before that change.

> Shouldn't then the `admin/files` route return `resource deleted` or something of sorts? There is no status code for this, unfortunately.

Knora deals with deleted items by pretending that they never existed, and returning 404 Not Found, with a message saying "X was not found (it may have been deleted)". I believe we originally decided that this would be safest from the point of view of privacy and possible legal issues. There's a related discussion in #1246.

> Ahh, a deleted resource. If we request the resource from a time before deletion, then the same question arises, right?

Currently there's no way to request the contents of a deleted resource (not even a past version from the time before deletion), and I actually think it shouldn't be allowed. In macOS, if you want to view a file that's in the trash, you have to move it out of the trash first.

Screen Shot 2019-05-24 at 16 07 18

Otherwise, "deleted" wouldn't mean much.

Years ago I asked @lrosenth whether he thought there should be a way to undelete things, and he said no, but you should be able to copy the contents of a deleted resource into a new resource. There's an issue for this: #1218.

**Comment by subotic** [comment]
thanks for the clarifications.

**Comment by benjamingeer** [comment]
Thanks for the review!

**Comment by benjamingeer** [comment]
Now I realise I need to make another PR for the case where you request an image from a past version of a resource...

**Comment by benjamingeer** [comment]
#1331

**Pull request merged**
