### PR TITLE
feature(webapi): Add returning of fixed public user information

### LINKED ISSUE #1220: Minimal user's informations
Due to PR #1208, it seems to me that we don't have any more informations about any user.
Is there a way to get the username/givenName/familyName from a user's IRI (`knora-api:attachedToUser`) to simply print out in a UI who is the  Resource creator for example?

Maybe related to #1214 ? (probably same use case, nice to have the history but without minimal informations about users, doesn't make sense for UI)

n.b. : we can still display user's name in Salsah by using the v1 API on value which returns `valuecreatorname` and `valuecreator`.

### PR DESCRIPTION
**Pull request by subotic**
resolves #1220 for now

### CODE REVIEW

**Comment by subotic** [comment]
Very simple implementation. The user itself and the SystemAdmin see everything. Everybody else sees only the public information.

**Comment by subotic** [comment]
Docs are updated

**Comment by subotic** [comment]
Thanks for the review :-)

**Comment by gfoo** [comment]
works for me, thanks!

**Pull request merged**
