### PR TITLE
Leibniz ontology 

### PR DESCRIPTION
**Pull request by SepidehAlassi**
- adds ontology for BEOL-Leibniz connection

### CODE REVIEW

**Comment by SepidehAlassi** [comment]
@tobiasschweizer for the next import this PR is needed.

**Comment by tobiasschweizer** [comment]
@SepidehAlassi So this PR just adds the new ontology for Leibniz?

**Comment by SepidehAlassi** [comment]
@tobiasschweizer yes

**Comment by SepidehAlassi** [comment]
@tobiasschweizer I wanted to do the refactoring of the ontologies in this branch, but realised that would need some changes also in GUI which would take long. So for now, it is better to first import Leibniz data also to beol server, and take care of refactoring later.

**Comment by tobiasschweizer** [comment]
got it, thanks for the clarification

**Comment by SepidehAlassi** [comment]
@tobiasschweizer yes, you need this for the data on the switchdrive
Thanks for checking this PR, As soon as travis is done with the checks I will merge this.

**Comment by tobiasschweizer** [comment]
Thanks. I will also convert the data according to https://github.com/dhlab-basel/Knora/pull/1322 and put the converted data back on switchdrive as a separate file.

**Comment by tobiasschweizer** [comment]
@SepidehAlassi I think your are good to merge!

**Pull request merged**
