### PR TITLE
Change all xsd:dateTimeStamp to xsd:dateTime in the triplestore

### PR DESCRIPTION
**Pull request by benjamingeer**
To implement version history (#1115), we need to be able to compare timestamps in the triplestore. So far we have used [xsd:dateTimeStamp](https://www.w3.org/TR/xmlschema11-2/#dateTimeStamp), but it turns out that SPARQL supports comparisons with `xsd:dateTime` but not with `xsd:dateTimeStamp`. So this PR changes `xsd:dateTimeStamp` to `xsd:dateTime` in:

- `knora-base`
- Test data
- Twirl templates that generate SPARQL

The only difference between the two types is that in `xsd:dateTimeStamp`, the timezone is required. All the timestamps generated by Knora specify the UTC timezone (`Z`) in any case.

We can still use `xsd:dateTimeStamp` in the API.

Users will have to change their own data, but this is very easy to do (just dump to Turtle and do a search-and-replace).

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@benjamingeer In my data, I just need to change `xsd:dateTimeStamp` to `xsd:dateTime`?

Example from my data: `"2017-11-29T12:01:47.467Z"^^xsd:dateTimeStamp .`

I assume that the format of the timestamp (YYYY-MM-DDT...Z) itself was never changed since mid 2016.

**Comment by benjamingeer** [comment]
@tobiasschweizer That's right.

**Comment by benjamingeer** [comment]
@subotic Whenever you get a chance. :)

**Comment by subotic** [comment]
sorry, didn’t see the review request. will do it tomorrow.

**Pull request merged**
