### PR TITLE
Update docs with new names

### PR DESCRIPTION
**Pull request by benjamingeer**
- KnarQL is now called Gravsearch.
- The Knora API server is now just called Knora.
- Restructure the docs somewhat as a result.
- Correct a few errors and out-of-date things in the docs.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
I will review it tomorrow morning :-)

**Comment by tobiasschweizer** [comment]
@benjamingeer https://github.com/dhlab-basel/Knora/pull/867/commits/f003b9911b4044a0471b3511899eabaefe2015d9 fixes the format documentation in typescript. Basically, the sample data is expected to be expanded (expanded prefixes).

If you want to document the format with the context object, this would have to be defined as a member of the interfaces.

**Comment by tobiasschweizer** [comment]
I think in the tests we should build the docs with

`typedoc --out target/site/api-v2 --readme none --name "Knora API V2 JSON-LD Format Documentation" --module commonjs src/api-v2`

In case typescript throws an error, this means that the sample responses are not valid.

**Comment by benjamingeer** [comment]
> the sample data is expected to be expanded (expanded prefixes).

Thanks. Somehow I ran `typedoc` yesterday as you said and got no errors, but I've just tried again and got errors, so I don't know what happened.

> I think in the tests we should build the docs with

That would be great. @subotic could Travis do this?

**Comment by tobiasschweizer** [comment]
> Thanks. Somehow I ran typedoc yesterday as you said and got no errors, but I've just tried again and got errors, so I don't know what happened.

Maybe you ran v1 by accident :-)

**Comment by benjamingeer** [comment]
> Maybe you ran v1 by accident

Probably!

**Comment by tobiasschweizer** [comment]
Otherwise this PR looks fine to me.

**Comment by benjamingeer** [comment]
> Otherwise this PR looks fine to me.

Could you possibly approve it then so I can merge it?

**Comment by benjamingeer** [comment]
Done. Thanks!

**Pull request merged**
