### PR TITLE
Create and update values in API v2, part 1

### LINKED ISSUE #585: Ignore standoff UUIDs when looking for redundant or duplicate text values
We made this design decision: If you make a new version of a text value, you should be able to keep the same standoff UUIDs, and there should be a way to annotate standoff tags by referring to their UUIDs, so that the annotations would still be valid with successive versions of the text value. However, currently the SALSAH GUI doesn't receive or use these UUIDs, so new ones are automatically created for each version of the text value. This means that when the API server compares the old version with the new one to check for duplicate or redundant text values, they're always different.

Since UUIDs aren't supported in v1, we should ignore them when doing these comparisons.

### LINKED ISSUE #952: Resource's last modification date not updated when creating a link in API v1

### LINKED ISSUE #970: Fix bugs related to the creation/deletion of link properties
* When a class is created with a cardinality for a link property, check that there's a cardinality for the corresponding link value property, and vice versa.
* When deleting a link property, delete the corresponding link value property.
* Don't allow a link value property to be deleted directly.

### PR DESCRIPTION
**Pull request by benjamingeer**
- [x] Implement code in `ValueMessagesV2` to read JSON-LD representing value update requests.
  - [x] `DateValueContentV2`
  - [x] `IntegerValueContentV2`
  - [x] `TextValueContentV2`
  - [x] `DecimalValueContentV2`
  - [x] `BooleanValueContentV2`
  - [x] `GeomValueContentV2`
  - [x] `IntervalValueContentV2`
  - [x] `HierarchicalListValueContentV2`
  - [x] `ColorValueContentV2`
  - [x] `UriValueContentV2`
  - [x] `GeonameValueContentV2`
  - [x] `LinkValueContentV2`
- [x] Include more metadata about resources and values in API responses.
  - [x] For resources and values:
    - [x] `attachedToUser`
    - [x] `hasPermissions`
    - [x] `isDeleted`, `deleteDate`, `deleteComment`
  - [x] For resources:
    - [x] `attachedToProject`
    - [x] `creationDate`
    - [x] `lastModificationDate`
  - [x] For values:
    - [x] `valueHasComment`
- [x] Fix JSON-LD representation of `xsd:decimal` and `xsd:anyURI` in the complex schema **(requires change in Salsah)**
- [x] Start implementing updates in `ValuesResponderV2`.
  - [x] create a new value
  - [x] create a value with custom permissions
  - [x] create a new link
- [x] Add a value update route.
- [x] Add tests.

Design strategy:

* Borrow code from `ValuesResponderV1`, refactoring to use functionality already available in v2
* Don't write SPARQL for querying values, use Gravsearch instead
* Reuse SPARQL update code from v1

For a subsequent PR:

* Update an existing value.
* Update an existing link.
* Add docs.
* Enable `ValuesResponderV2` to generate SPARQL `INSERT` code to create multiple values.
* Handle update requests that submit files.
* Mark values as deleted.

Fixes #585.
Fixes #952.
Fixes #970.

### CODE REVIEW

**Comment by benjamingeer** [comment]
@subotic Do I have to get a Codecov report for every commit? This is very noisy.

**Comment by benjamingeer** [comment]
@subotic Is GitHub saying I can't merge because Codecov says code coverage is too low?

**Comment by benjamingeer** [comment]
TODO:

* Uncomment geometry values in the `anything` ontology
* Support interval and geoname values in Gravsearch

**Comment by tobiasschweizer** [comment]
I will make the necessary changes in the Salsah repo tomororow, see 
https://github.com/dhlab-basel/Salsah/issues/281, otherwise this PR is blocked.

In parallel, the same change is made for knora-ui @kilchenmann @flavens

**Comment by benjamingeer** [comment]
@tobiasschweizer Any chance I could merge this today?

**Comment by tobiasschweizer** [comment]
That's ok with me!

Please also merge https://github.com/dhlab-basel/Salsah/pull/287 once you have merged this PR.

**Comment by benjamingeer** [comment]
Thanks @subotic for the review and @tobiasschweizer for the help!

**Pull request merged**
