### PR TITLE
test(api-v2): Test an ontology with only one entity

### LINKED ISSUE #1428: Test JSON-LD rendering of an ontology containing only one entity
In response to a question from @tobiasschweizer .

### PR DESCRIPTION
**Pull request by benjamingeer**
- [x] Add `minimal-onto.ttl` and test how it's served in JSON-LD (always with `@graph`).
- [x] When updating test response files in `OntologyV2R2RSpec`, don't update RDF/XML files if only their blank node IDs have changed (makes it easier to check the really changed files into git).
- [x] Remove a generated client code file from git (this was causing confusing random errors in the client code test).

Resolves #1428.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
Thanks! I will try that JSOn-LD in knora-api-lib-js.

**Comment by tobiasschweizer** [comment]
I have added this in https://github.com/dhlab-basel/knora-api-js-lib/pull/28

**Comment by benjamingeer** [comment]
> So  "@graph" is also an array if it contains just one element?

Yes, Knora always inserts `@graph` in an ontology response, and the JSON-LD processor will keep the `@graph` if there is something else at the top level (you can see this behaviour in the JSON-LD Playground). The JSON-LD processor moves the contents of `@graph` to the top level only if the graph contains one node and document contains nothing else.

**Comment by benjamingeer** [comment]
Thanks!

**Comment by tobiasschweizer** [comment]
Thank you, you are a true minimalist!

**Comment by benjamingeer** [comment]
https://www.youtube.com/watch?v=doJk4yPwJDk

**Comment by tobiasschweizer** [comment]
I know Steve Reich :-)

**Pull request merged**
