### PR TITLE
build (travis): change sipi docker command

### LINKED ISSUE #900: Sipi failed to start on Travis
The Sipi docker image definition changed, which now requires a slightly different invocation.

### PR DESCRIPTION
**Pull request by subotic**
### Summary

- Update Sipi invocation command.
- Update docs.

### Issues

- resolves #900

### CODE REVIEW

**Comment by subotic** [comment]
@benjamingeer this should fix the issue. Locally you need to type: `docker image rm --force dhlabbasel/sipi:develop` so that when you run the new command locally, the new image is pulled. Travis pulls the image every time. That is why it worked locally but not on Travis.

**Comment by benjamingeer** [comment]
> Locally you need to type: `docker image rm --force dhlabbasel/sipi:develop` 

Should that be added to the docs?

**Comment by subotic** [comment]
The problem is that I don't know where to put it. This is so generall Docker stuff. Potentially everywhere a docker image is pulled, this command will maybe be needed. It's like `rm` in `bash` (hence the name).

**Comment by subotic** [comment]
added rm command to the docs ;-)

**Comment by benjamingeer** [comment]
Perfect, thanks!

**Pull request merged**
