### PR TITLE
Apache Lucene support: unfify v1 and v2

### LINKED ISSUE #1377: Refactor Lucene processing in v1 and v2
* According to #1196, the user is supposed to be able to submit `***` as a search string and get any resource. But the [Lucene syntax documentation](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Wildcard%20Searches) says that you can't use `*` as the first character of a search string. For some reason, `***` seems to work anyway on GraphDB, but it doesn't work on Fuseki, which I'm trying to support again (#1375).
* Perhaps we should start using the [GraphDB Lucene Connector](http://graphdb.ontotext.com/documentation/standard/lucene-graphdb-connector.html).
* #641

### PR DESCRIPTION
**Pull request by tobiasschweizer**
This PR refactors the Apache Lucene utilty class, adds tests to it, and uses it also from v1 templates.

The [Lucene query syntax](https://lucene.apache.org/core/7_7_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html) will be accepted directly in fulltext searches without any preprocessing involved.

closes #1377

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
I think GraphDB Lucene Connector should be added in a separate PR. It does not affect the way search strings are preprocessed to make use of the Lucene syntax.

**Comment by tobiasschweizer** [comment]
I identified a problem with `CombineSearchTerms.combineSearchTermsWithLogicalAnd`:

The method does not take into account phrases, everyting is treated as a term, e.g. `"Leonhard Euler"` becomes `"Leonhard AND Euler"`

**Comment by tobiasschweizer** [comment]
Lucene docs: https://lucene.apache.org/core/7_7_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#Terms

**Comment by tobiasschweizer** [comment]
@benjamingeer I will try to finish this PR today so the integration of Jena Fuseki #1375 is not blocked any longer.

**Comment by tobiasschweizer** [comment]
> Can you fix it?

No, because this would require to parse a Lucene query and understand its meaning. I would rather be inclined to say that for standoff searches we only support a single term or a phrase, i.e. several terms in quoted string.

That would have consequences for:
 - Gravsearch standoff search
- fulltext search when a standoff class is submitted as a param

**Comment by benjamingeer** [comment]
> I would rather be inclined to say that for standoff searches we only support a single term or a phrase, i.e. several terms in quoted string.

OK!

**Comment by tobiasschweizer** [comment]
But I will do it in a subsequent PR, so this damn thing can be merged soon. I am working on the docs now.

**Comment by tobiasschweizer** [comment]
@benjamingeer Ok, this PR is ready to be reviewed. I will do #1448 after I am back from my holidays in three weeks.

@flavens @kilchenmann the Knora docs contain references to the [Lucene Query Parser Syntax](https://lucene.apache.org/core/7_7_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html).  In the GUI, we need something that facilitates the generation of szch a search, see https://discuss.dasch.swiss/t/use-lucene-syntax-in-fulltext-search/81.

**Comment by tobiasschweizer** [comment]
I restarted the processes on travis ...

**Comment by tobiasschweizer** [comment]
ok, the tests passed ...
it's writing the damn coverage report ...

**Comment by tobiasschweizer** [comment]
mörtsched!!!!!!!!!!!!

**Pull request merged**
