### PR TITLE
fix (invalid mapping Iri):

### PR DESCRIPTION
**Pull request by tobiasschweizer**
throw an error when the user provides an invalid mapping Iri

@loicjaouen Could you please try to do the thing you did on this branch and see if you get an apt error message?

### CODE REVIEW

**Comment by loicjaouen** [comment]
# test

```sh
$ curl -X POST http://localhost:3333/v1/mapping \
    -u 'anything.user02@example.org:test' \
    -H 'content-type: multipart/form-data' \
    -F xml=@/Users/ljaouen/Soft/Code/github/KnoraBasle/webapi/_test_data/test_route/texts/mappingForHTML.xml \
   -F 'json={
    "project_id": "http://data.knora.org/projects/anything",
    "label": "mapping for HTML",
    "mappingName": "HTMLMapping"
}'
```
result:
```json
{"mappingIri":"http://data.knora.org/projects/anything/mappings/HTMLMapping","status":0}
```

creation of a resource with a wrong mapping:
```sh
$ curl -X POST \
   'http://localhost:3333/v1/resources' \
   -u 'anything.user02@example.org:test' \
   -H 'Content-Type: application/json' \
   --data '{
     "restype_id": "http://www.knora.org/ontology/anything#Thing",
     "properties": {
         "http://www.knora.org/ontology/anything#hasText": [{
             "richtext_value": {"utf8str": "test mapping"}
         }],
         "http://www.knora.org/ontology/anything#hasRichtext": [{
                 "richtext_value": {
                     "xml": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<text><p>test mapping</p></text>",
                     "mapping_id": "http://data.knora.org/projects/standoff/mappings/HTMLMapping"
                 }
         }]
     },
     "project_id": "http://data.knora.org/projects/anything",
     "label": "test mapping"
 }'
```

response:
```sh
{"status":11,"error":"org.knora.webapi.BadRequestException: mapping http://data.knora.org/projects/standoff/mappings/HTMLMapping does not exist"}
```

# conclusion

this is much better :)

**Comment by tobiasschweizer** [comment]
@loicjaouen Would you like the user to get insulted by Knora when he provides an invalid mappingIri (you could set aggressiveness of Knora in the config)? ;-)

**Comment by loicjaouen** [comment]
I can now immediately see that I got it wrong in my understanding that all standoff mappings would go under `http://data.knora.org/projects/standoff/mappings/` and that therefore, I was blind to spot the difference between the result mapping IRI and the one I figured out.

@tobiasschweizer : of course, insults help, but also flashing subliminal messages on the screen  or electric shocks through the keyboard... but you then have to review the license terms to warn against heart attack risks.

**Comment by tobiasschweizer** [comment]
> of course, insults help, but also flashing subliminal messages on the screen or electric shocks through the keyboard... but you then have to review the license terms to warn against heart attack risks. 

:-)

> I can now immediately see that I got it wrong in my understanding that all standoff mappings would go under http://data.knora.org/projects/standoff/mappings/

Do you think that should be clarified in the docs?

**Comment by tobiasschweizer** [comment]
actually I documented it :-)

> A successful response returns the Iri of the mapping. However, the Iri of a mapping is predictable: it consists of the project Iri followed by /mappings/ and the mappingName submitted in the JSON (if the name already exists, the request will be rejected).

**Pull request merged**
