### PR TITLE
test (webapi): add E2E testing

### PR DESCRIPTION
**Pull request by subotic**
This pull-request breaks out E2E testing out of pull-request #168

- f: modularize knora service startup
- t: renamed / moved E2ESpec to R2RSpec:
  * R2R - Route-to-Responder (still only internal testing, can but need not be backed by triplestore)
  * E2E - End-to-End (access only over HTTP and by design is always backed by triplestore)
- t: Authentication: renamed existing test to R2R and added E2E test
- t: StoreRoute: changed existing test (StoreRouteV1E2ESpec) to only use HTTP
- t: add E2ESpec class, which can be used to run E2E tests. For a full example of how to use it, see 'StoreRouteV1E2ESpec'

### CODE REVIEW

**Comment by subotic** [comment]
There seems to be a problem with the incunabula data with turned on consistency checking:

```
[info] - Load test data *** FAILED *** (12 seconds, 888 milliseconds)
[2016-08-25 18:51:59,127] ERROR Dispatcher - org-knora-webapi-e2e-v1-SipiV1E2ESpec-akka.actor.default-dispatcher-4 - akka.dispatch.Dispatcher - Failed to execute insert into triplestore
org.knora.webapi.TriplestoreResponseException: Failed to execute insert into triplestore
	at org.knora.webapi.TriplestoreResponseException$.apply(Exceptions.scala:229) ~[classes/:na]
	at org.knora.webapi.store.triplestore.http.HttpTriplestoreActor.org$knora$webapi$store$triplestore$http$HttpTriplestoreActor$$insertDataIntoTriplestore(HttpTriplestoreActor.scala:276) ~[classes/:na]
	at org.knora.webapi.store.triplestore.http.HttpTriplestoreActor$$anonfun$3.apply(HttpTriplestoreActor.scala:248) ~[classes/:na]
	at org.knora.webapi.store.triplestore.http.HttpTriplestoreActor$$anonfun$3.apply(HttpTriplestoreActor.scala:245) ~[classes/:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) ~[akka-actor_2.11-2.4.0.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.4.0.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.4.0.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.4.0.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) ~[scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) ~[akka-actor_2.11-2.4.0.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[akka-actor_2.11-2.4.0.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:399) ~[akka-actor_2.11-2.4.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: org.knora.webapi.TriplestoreResponseException: Unable to load file _test_data/all_data/incunabula-data.ttl; triplestore responded with HTTP code 500: org.openrdf.repository.RepositoryException: org.openrdf.sail.SailException: java.lang.Exception: Consistency check subject_class_constraint_1 failed:
http://data.knora.org/8a0b1e75 http://www.knora.org/ontology/incunabula#description http://data.knora.org/8a0b1e75/values/3e3d4dc0e922
http://www.knora.org/ontology/incunabula#description http://www.knora.org/ontology/knora-base#subjectClassConstraint http://www.knora.org/ontology/knora-base#Resource
-----------------------------------
http://data.knora.org/8a0b1e75 http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://www.knora.org/ontology/knora-base#Resource
```

@benjamingeer @tobiasschweizer Can I ignore this, or did I brake something? I didn't touch the incunabula data. Or am I supposed to turn off consistency checking?

**Comment by benjamingeer** [comment]
We haven't seen this error. It looks like it's because you removed the lines that load the Knora ontologies in the tests. On `develop` we have:

```
    val rdfDataObjects = List(
        RdfDataObject(path = "../knora-ontologies/knora-base.ttl", name = "http://www.knora.org/ontology/knora-base"),
        RdfDataObject(path = "../knora-ontologies/knora-dc.ttl", name = "http://www.knora.org/ontology/dc"),
        RdfDataObject(path = "../knora-ontologies/salsah-gui.ttl", name = "http://www.knora.org/ontology/salsah-gui"),
        RdfDataObject(path = "_test_data/ontologies/incunabula-onto.ttl", name = "http://www.knora.org/ontology/incunabula"),
        RdfDataObject(path = "_test_data/all_data/incunabula-data.ttl", name = "http://www.knora.org/data/incunabula"),
        RdfDataObject(path = "_test_data/ontologies/images-demo-onto.ttl", name = "http://www.knora.org/ontology/images"),
        RdfDataObject(path = "_test_data/demo_data/images-demo-data.ttl", name = "http://www.knora.org/data/images")
    )
```

On `wip/subotic_e2e_testing` you have:

```
    val rdfDataObjects = List(
        RdfDataObject(path = "_test_data/ontologies/incunabula-onto.ttl", name = "http://www.knora.org/ontology/incunabula"),
        RdfDataObject(path = "_test_data/all_data/incunabula-data.ttl", name = "http://www.knora.org/data/incunabula"),
        RdfDataObject(path = "_test_data/ontologies/images-demo-onto.ttl", name = "http://www.knora.org/ontology/images"),
        RdfDataObject(path = "_test_data/demo_data/images-demo-data.ttl", name = "http://www.knora.org/data/images")
    )
```

If `knora-base.ttl` is not loaded, there's no way for the consistency checker to know that `incunabula:page` is a subclass of `knora-base:Resource`.

**Comment by subotic** [comment]
I'm stupid. My bad. I copied the tests over from my ``wip/user_management`` branch. There I changed the way the triplestore is reloaded so that the base ontologies don't need to be listed. That's why they are missing here.

Thanks :-)

**Comment by benjamingeer** [comment]
No problem. :)

**Comment by subotic** [comment]
This is now ready for review.

**Comment by benjamingeer** [comment]
This looks great, please merge!

**Comment by subotic** [comment]
thanks :-)

**Pull request merged**
