### PR TITLE
releasing v1.2.0

### PR DESCRIPTION
**Pull request by subotic**
Following steps from #735

- [x] Create a new branch, e.g., releasing-v1.2.0
- [x] Update the version number in `WebapiBuild.sbt`, `SalsahBuild.sbt`, `conf.py`
- [x] Check if all release notes are there. They should be added as part of the pull-request introducing any code changes
- [x] Remove the (not released yet) text in the title of the release notes
- [x] Create a new page with the next version number including the (not released yet) text and add page to TOC
- [x] Move any open issues from current release to the next release.

### CODE REVIEW

**Comment by benjamingeer** [comment]
Something I forgot to add to the release notes: you have to replace the `salsah-gui` ontology that you have in the triplestore with the one in `salsah-gui.ttl`.

**Comment by subotic** [comment]
done ;-)

**Comment by benjamingeer** [comment]
Thanks! :)

**Comment by subotic** [comment]
If you like you can review :-)

**Comment by subotic** [comment]
thanks :-)

**Pull request merged**
