### PR TITLE
Wip/authentication

### PR DESCRIPTION
**Pull request by subotic**
Ben,

As far as I can tell the authentication issue is fixed. I also added tests that catch the error.

These tests should pass, but there seems to be another problem with the returned HTTP status code. The code that I expect is 401 (as with all BadCredentialExceptions) but 400 is returned. I cannot find where the problem is. Can you maybe take a look?

The test in question is ```AuthenticationV1E2ESpec.scala```.

### CODE REVIEW

**Comment by subotic** [comment]
Contains fixes for #13 and #40

**Comment by benjamingeer** [comment]
I'm looking into the 400 vs. 401 error now, but in the meantime, I have a suggestion: [let's not use SHA-1](https://en.wikipedia.org/wiki/SHA-1).

> SHA-1 is no longer considered secure against well-funded opponents. In 2005, cryptanalysts found
> attacks on SHA-1 suggesting that the algorithm might not be secure enough for ongoing use, and
> since 2010 many organizations have recommended its replacement by SHA-2 or SHA-3.
> Microsoft, Google and Mozilla have all announced that their respective browsers will
> stop accepting SHA-1 SSL certificates by 2017.

**Comment by subotic** [comment]
Yes, I agree. The only reason why we use SHA-1 is that the demo data comes like this. Beside SHA-1 we have already implemented BCrypt. According to this [blogpost](https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016) BCrypt seems to be acceptable. Apparently Argon2 is now the top dog. The libsodium library that they recommend is written in C, so we would need to find a Java/Scala implementation of Argon2 or write it ourselves.

**Comment by benjamingeer** [comment]
There's a Java binding for the C implementation of Argon2, which runs on Linux and Mac OS X:

https://github.com/phxql/argon2-jvm

**Comment by subotic** [comment]
Cool. Shall we then use Argon2? On the other hand, this will make using Knora a bit more difficult, i.e. this library would need to be installed first. Maybe for now BCrypt is more than sufficient?

**Comment by benjamingeer** [comment]
I guess if bcrypt is good enough for BSD it's good enough for us. But:

http://blog.ircmaxell.com/2012/12/seven-ways-to-screw-up-bcrypt.html

**Comment by subotic** [comment]
Very interesting blog post, thanks.
At the moment we don't actually have a way of creating new users. Maybe I can start a route and extend the users responder so that we can actually create new users?

**Comment by benjamingeer** [comment]
I fixed the incorrect HTTP status code, it was a bug in `ApiStatusCodesV1.fromException`. `BadCredentialsException` is a subclass of `RequestRejectedException`, but `RequestRejectedException` was first in the match-case expression, so `BadCredentialsException` was never matched. Now you should get the 401 status code.

**Comment by subotic** [comment]
cool, thanks :-)

**Comment by benjamingeer** [comment]
> Maybe I can start a route and extend the users responder so that we can actually create new users?

Good idea!

This pull request looks good to me, you can go ahead and merge it.

**Comment by subotic** [comment]
Thanks. I will clean up first (log levels, etc.) and then merge.

**Comment by subotic** [comment]
I have added a few more test cases surrounding cookie/session handling and dialed down the log levels. If it's ok, I will merge it.

**Comment by benjamingeer** [comment]
Looks good, could you just add Scaladoc comments to `SessionResponse` and `MyJsonSessionResponseProtocol` to explain what they are, and maybe think of a clearer name for the latter? (Why is it called `My` something?) Then you can go ahead and merge.

**Comment by subotic** [comment]
Better?

**Comment by benjamingeer** [comment]
Great, thanks! Looks good to merge now.

**Comment by subotic** [comment]
fixes #13 
fixes #40

**Pull request merged**
