### PR TITLE
Bug/search list

### LINKED ISSUE #800: wrong search result with two list values
- let's start with a `anything:Thing` that has two list elements:
capture d ecran 2018-03-28 a 15 16 48

- let's make a request on the first list element

  http://localhost:3333/v1/search/?searchtype=extended&property_id=http%3A%2F%2Fwww.knora.org%2Fontology%2Fanything%23hasListItem&compop=EQ&searchval=http%3A%2F%2Fdata.knora.org%2Fanything%2FtreeList01&show_nrows=25&start_at=0&filter_by_restype=http%3A%2F%2Fwww.knora.org%2Fontology%2Fanything%23Thing

  There is one result.

- then a request on the second list

  http://localhost:3333/v1/search/?searchtype=extended&property_id=http%3A%2F%2Fwww.knora.org%2Fontology%2Fanything%23hasOtherListItem&compop=EQ&searchval=http%3A%2F%2Fdata.knora.org%2Fanything%2FotherTreeList02&show_nrows=25&start_at=0&filter_by_restype=http%3A%2F%2Fwww.knora.org%2Fontology%2Fanything%23Thing

  There is still one result, the same

- finally a request on both of them, the result set is empty

  http://localhost:3333/v1/search/?searchtype=extended&property_id=http%3A%2F%2Fwww.knora.org%2Fontology%2Fanything%23hasListItem&property_id=http%3A%2F%2Fwww.knora.org%2Fontology%2Fanything%23hasOtherListItem&compop=EQ&compop=EQ&searchval=http%3A%2F%2Fdata.knora.org%2Fanything%2FtreeList01&searchval=http%3A%2F%2Fdata.knora.org%2Fanything%2FotherTreeList02&show_nrows=25&start_at=0&filter_by_restype=http%3A%2F%2Fwww.knora.org%2Fontology%2Fanything%23Thing

  There is no result!

All three requests are visible here:

capture d ecran 2018-03-28 a 15 20 36

### PR DESCRIPTION
**Pull request by loicjaouen**
demonstrates #800 
... and fixes #800

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@loicjaouen Do I understand correctly that tis PR adds tests to make a bug visible?

**Comment by tobiasschweizer** [comment]
OK :-)

**Comment by loicjaouen** [comment]
I assigned the issue to @benjamingeer hoping he could have a look (without asking him)... now if you show interest, you might want to look at it?

**Comment by loicjaouen** [comment]
i did have a look but I got lost, I don't understand twirl, and actually never learned scala, only bought books which I had no time to read so far

**Comment by tobiasschweizer** [comment]
just print out the generated SPARQL so we can have a look at it

**Comment by loicjaouen** [comment]
did you read that "just" post from @benjamingeer ?

ok, I wrote down somewhere how to log the sparql queries and will do that

**Comment by tobiasschweizer** [comment]
> ok, I wrote down somewhere how to log the sparql queries and will do that

the SPARQL query is stored in some variable, *just* `println(query)` and get rid of the string "webapi"

**Comment by loicjaouen** [comment]
here it is:
```sql
 prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
 prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 prefix knora-base: <http://www.knora.org/ontology/knora-base#>
 prefix xsd: <http://www.w3.org/2001/XMLSchema#>

 SELECT DISTINCT
     ?resource
     ?resourceLabel
     ?resourceClass
     ?previewPath
     ?previewDimX
     ?previewDimY
     ?resourceCreator
     ?resourceProject
     ?resourcePermissions

         ?valueObject0
         ?valueCreator0
         ?valuePermissions0
         ?targetResource0
         ?targetResourceCreator0
         ?targetResourceProject0
         ?targetResourcePermissions0
         ?literal0

         ?valueObject1
         ?valueCreator1
         ?valuePermissions1
         ?targetResource1
         ?targetResourceCreator1
         ?targetResourceProject1
         ?targetResourcePermissions1
         ?literal1

 WHERE {
     BIND(STR("en") AS ?preferredLanguage)
     BIND(STR("en") AS ?fallbackLanguage)



         # Search criterion 0: operator EQ





             ?resource <http://www.knora.org/ontology/anything#hasOtherListItem> ?valueObject0 .











                         ?valueObject0 knora-base:valueHasListNode ?listNode .
                         <http://data.knora.org/anything/otherTreeList02> knora-base:hasSubListNode* ?listNode .

                         ?listNode rdfs:label ?listNodeLabel .
                         BIND(?listNodeLabel AS ?literal0)




         ?valueObject0 knora-base:isDeleted false ;
             knora-base:attachedToUser ?valueCreator0 ;
             knora-base:hasPermissions ?valuePermissions0 .


         # Search criterion 1: operator EQ





             ?resource <http://www.knora.org/ontology/anything#hasListItem> ?valueObject1 .











                         ?valueObject1 knora-base:valueHasListNode ?listNode .
                         <http://data.knora.org/anything/treeList01> knora-base:hasSubListNode* ?listNode .

                         ?listNode rdfs:label ?listNodeLabel .
                         BIND(?listNodeLabel AS ?literal1)




         ?valueObject1 knora-base:isDeleted false ;
             knora-base:attachedToUser ?valueCreator1 ;
             knora-base:hasPermissions ?valuePermissions1 .


     ?resource knora-base:isDeleted false .



     GRAPH <http://www.ontotext.com/explicit> {
         ?resource a ?resourceClass .
     }



             # Filter by resource class.

             ?resource a <http://www.knora.org/ontology/anything#Thing> .





     ?resource rdfs:label ?resourceLabel .

     OPTIONAL {
         ?resource knora-base:hasStillImageFileValue ?fileValue .
         ?fileValue a knora-base:StillImageFileValue .
         ?fileValue knora-base:isPreview true .
         ?fileValue knora-base:internalFilename ?previewPath .

         OPTIONAL {
             ?fileValue knora-base:dimX ?previewDimX .
             ?fileValue knora-base:dimY ?previewDimY .
         }
     }

     ?resource knora-base:hasPermissions ?resourcePermissions ;
         knora-base:attachedToUser ?resourceCreator ;
         knora-base:attachedToProject ?resourceProject .
 }
 LIMIT 500
```

**Comment by loicjaouen** [comment]
isn't it that they use the same `?listNode` variable?

```
                         ?valueObject1 knora-base:valueHasListNode ?listNode1 .
```

should help

**Comment by tobiasschweizer** [comment]
> isn't it that they use the same ?listNode variable?

Maybe I forgot to add the counter to the variables. Could you try to figure out the correct SPARQL using the web console? Then I can help you fix it in twirl.

**Comment by loicjaouen** [comment]
it looks like: `searchExtendedGraphDB.scala.txt` line 258

**Comment by loicjaouen** [comment]
I try adding an `@index` where I feel like it might help...

**Comment by tobiasschweizer** [comment]
> I try adding an @index where I feel like it might help...

It should be pretty easy: whatever SPARQL variable needs to be unique needs an index in order to distinguish it from the others. Your feelings do not matter here ;-)

**Comment by loicjaouen** [comment]
local test is happier `graphdb:testOnly *SearchV1R2RSpec`:

```
[info] Total number of tests run: 14
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 14, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```

let's see the global tests for border effects

**Comment by benjamingeer** [comment]
This tells you why the test is failing:

```
- should search for an anything:Thing that may have a Boolean value that is true *** FAILED *** (255 milliseconds)
[info]   java.lang.AssertionError: assertion failed: numberOfItems did not match: expected 11, but received 12
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at org.knora.webapi.e2e.v2.ResponseCheckerR2RV2$.compareParsedJSONLD(ResponseCheckerR2RV2.scala:137)
[info]   at org.knora.webapi.e2e.v2.ResponseCheckerR2RV2$.compareJSONLD(ResponseCheckerR2RV2.scala:172)
[info]   at org.knora.webapi.e2e.v2.SearchRouteV2R2RSpec.$anonfun$new$72(SearchRouteV2R2RSpec.scala:1515)
```

`SearchRouteV2R2RSpec.scala` line 1515:

https://github.com/dhlab-basel/Knora/blob/c504636bebcceb41c05430a35a805db50a018716/webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala#L1515

That's comparing the response to the contents of the file `src/test/resources/test-data/searchR2RV2/ThingWithBooleanOptional.jsonld`.

So the contents of that file need to be updated.

**Comment by benjamingeer** [comment]
By the way, no need for `graphdb:testOnly`, because graphdb is the default now, so you can just use `testOnly`.

**Comment by loicjaouen** [comment]
@benjamingeer thanks :)

**Comment by benjamingeer** [comment]
Please just update the release notes to say that this bug has been fixed.

**Comment by loicjaouen** [comment]
welcome! and thanks for your help @benjamingeer and @tobiasschweizer  ;)

@benjamingeer : release note update, like this 68c0600 ?
Actually, should it really go to 1.4 or could we put that in an earlier 1.3.x ?

**Comment by benjamingeer** [comment]
> Actually, should it really go to 1.4 or could we put that in an earlier 1.3.x ?

@subotic ?

**Comment by subotic** [comment]
Please put it in 1.4. It is a pain to release, so next release is going to happen end of the month :-)

**Comment by loicjaouen** [comment]
This drowns me in a sea of indecision where I can't fully grasp the inputs of the decision process and their respective weights. 

We are still on 1.1.0 on our production plaftorm partly because we want to be on par with our UAT platform where we have UAT ongoing and evolving ontologies for projects soon to be promoted to prod and each release requires changes in config, data or ontologies.

But our users need this features for their research.

I am sorry to push some of our stress to you, but will the next release be 1.4 and will happen on end of April?

**Comment by subotic** [comment]
At the moment, releases are published once a month. You can always take `develop` and use it. I can tag this commit in `develop`, so you will get a docker image with this unique tag.

**Comment by loicjaouen** [comment]
@subotic thanks for the offer, yes, if you don't mind, please tag it, I prefer to base our docker images on official images.

That was somehow the meaning of my previous question ;)
>  Actually, should it really go to 1.4 or could we put that in an earlier 1.3.x ?

**Comment by subotic** [comment]
It's tagged. In a bit, you should have a docker image tagged as  `v1.3.1`

**Pull request merged**
