### PR TITLE
Rework the Knora development with IntelliJ documentation

### LINKED ISSUE #457: improve doc 'Setup IntelliJ for development of Knora'
the name of the project has changed, the procedure is slightly different on more recent versions of idea and we should add needed memory arguments

### PR DESCRIPTION
**Pull request by loicjaouen**
* Fixes #457 
* Adds a section on profiling using [VisualVM](https://visualvm.github.io/)

### CODE REVIEW

**Comment by benjamingeer** [comment]
Pull request #464 fixes the out-of-memory error when compiling `ResourcesResponderV1SpecContextData`, so once that's merged, you can remove the part about increasing the default memory settings in the VM options.

**Comment by loicjaouen** [comment]
good news!

**Comment by loicjaouen** [comment]
i just updated the screenshot without the memory setting and i will merge when the build is over (i.e. after lunch)

**Comment by loicjaouen** [comment]
Thanks @benjamingeer

**Pull request merged**
