### PR TITLE
docs(ark): Document ARK URLs for projects

### LINKED ISSUE #1407: Document ARK URLs for projects
Moved from #1406.

### PR DESCRIPTION
**Pull request by benjamingeer**
Resolves #1407.

Thanks @mrivoal for asking about this.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
Wouldn't it make more sense if @mrivoal has a look at this?

**Comment by benjamingeer** [comment]
@mrivoal Does this tell you what you need to know?

**Comment by mrivoal** [comment]
> Does this tell you what you need to know?

Yes, it does. I was only unsure about the `version` of a project but I guess there will be various versions of a project description, so that makes perfect sense.

**Comment by benjamingeer** [comment]
@mrivoal Sorry, I will clarify that. It isn't the version of the project, but the version of the Knora ARK URL format (currently always 1).

**Comment by benjamingeer** [comment]
@mrivoal And thanks for the review!

**Comment by mrivoal** [comment]
My very first one on Knora :)

**Pull request merged**
