### PR TITLE
feature (docker): add docker support for graphdb and fuseki

### PR DESCRIPTION
**Pull request by subotic**
This pull-request is a first in a series to brake up pull-request #168 

Adding docker support, so that fuseki and graphdb can be run inside a container on a local machine. This makes setting up a developer machine much easier. Also, running graphdb inside a docker container is piece in the puzzle of the Knora deployment (#3).

### CODE REVIEW

**Comment by subotic** [comment]
This pull-request is ready for review.

**Comment by benjamingeer** [comment]
This is very nice!

I think all the documentation should be in the RST files in `docs`, e.g. under `knora-api-server/deployment`, rather than in separate Markdown files under `triplestores`. This would make it easier to find, because users are going to look for documentation first in the main documentation tree. We also need to be able to package up all the Knora documentation as a single PDF or a single set of HTML files so we can put it on line.

In `docs/rst/knora-api-server/development/build-process.rst`, there is a TODO: `Using docker for all of the above`. Is that TODO now done?

`triplestores/graphdb-se-6/README.md` says to copy `KnoraRules.pie` into that folder, but you've already done that it and put it in git, so there seems to be no reason for the user to copy it.

This is confusing:

```
$ docker build -t graphdb <path-to-dockerfile>
```

If I'm in the `graphdb-se-6` directory and I type that command, this happens:

```
$ docker build -t graphdb ./Dockerfile 
unable to prepare context: context must be a directory: /Users/benjamingeer/git/Knora/triplestores/graphdb-se-6/Dockerfile
```

After some experimentation, I figured out that it needs the path to the directory that contains `Dockerfile`, not the path to `Dockerfile` itself.

The **Advanced Usage** sections of the documentation could use some brief explanations. What is the difference between `run` and `start`? When would you use `attach`?

**Comment by subotic** [comment]
@benjamingeer Could you maybe try the Sipi docker image out, and see if the documentation is somewhat clear?

**Comment by benjamingeer** [comment]
I'll try it, thanks!

**Comment by subotic** [comment]
I have rebased this branch (``wip/subotic_docker``) onto ``develop`` to pull in the newest commits. Since this rewrote the history on this branch, I needed to do a force push. So far github doesn't seem to mind. You will probably need to delete your local version and do a checkout again.

**Comment by subotic** [comment]
It is ready for review

**Comment by benjamingeer** [comment]
OK, this looks great to me. Only problem: when I build the HTML docs, I get these errors because of undefined references:

```
/Users/benjamingeer/git/Knora/docs/rst/knora-api-server/development/overview.rst:46: ERROR: Unknown target name: "free software".
/Users/benjamingeer/git/Knora/docs/rst/knora-api-server/development/overview.rst:50: ERROR: Unknown target name: "ontotext graphdb".
/Users/benjamingeer/git/Knora/docs/rst/knora-api-server/development/overview.rst:54: ERROR: Unknown target name: "apache jena".
/Users/benjamingeer/git/Knora/docs/rst/knora-api-server/development/overview.rst:54: ERROR: Unknown target name: "free software".
```

Please just fix these, and then go ahead and merge.

**Pull request merged**
