### PR TITLE
feature (config): graphdb repository type

### LINKED ISSUE #898: Use  owlim:MonitorRepository as repository type
It seems that we initialize our repositories in the wrong way. We have `rep:repositoryType "openrdf:SailRepository" ;` but according to Ontotext we should have `rep:repositoryType "owlim:MonitorRepository"`.  At least, this was the explanation given by them for a ticket that I opened regarding backup restore.

- http://graphdb.ontotext.com/documentation/standard/configuring-a-repository.html#configure-a-repository-programmatically

### PR DESCRIPTION
**Pull request by subotic**
### Summary
- change repository type to `owlim:MonitorRepository`
- change required repository type during startup-checks to `owlim:MonitorRepository`
- update Travis GraphDB-SE to `8.6.0`
  - From the Release notes: update to latest RDF4J 2.3.2 version which in turn has experimental SHACL support. So I suppose that GraphDB now has SHACL support.

### Issues
- resolves #898

### CODE REVIEW

**Comment by subotic** [comment]
giving up on #918

**Comment by subotic** [comment]
Thanks for the review :-)

Yes, it was/is a bit frustrating. A lot of time spent on not much output. On top of that, some tests are now failing on Travis, although all tests are passing on my local machine. Oh well, maybe it will fix itself until tomorrow.

**Comment by subotic** [comment]
Now we have a problem. None of the memory settings work on Travis. Before we could run GraphDB with 2GB of RAM defined through the `GDB_HEAP_SIZE` environment variable. On my notebook, a simple test like the `org.knora.webapi.store.triplestore.AllTriplestoreSpec` now requires a minimum value of `3400m`, but this value is too high for Travis. This is very irritating.

**Comment by benjamingeer** [comment]
I've noticed that the latest version of GraphDB takes more memory than previous versions, too.

**Comment by subotic** [comment]
@benjamingeer Unbelievable. The tests pass finally. Could you maybe take a look? I had to regenerate some test data.

**Comment by subotic** [comment]
@benjamingeer is it OK to merge?

**Comment by subotic** [comment]
yes, a bit ;-)

**Comment by subotic** [comment]
thanks :-)

**Comment by subotic** [comment]
@benjamingeer I don't know if you saw, that GraphDB now supports SHACL.

**Comment by benjamingeer** [comment]
@subotic Very interesting! I can't find any documentation about it, though (in the GraphDB docs), have you seen any?

**Comment by subotic** [comment]
@benjamingeer saw it only in the [Release Notes](http://graphdb.ontotext.com/documentation/standard/release-notes.html#component-versions). RDF4J has some [documentation](http://docs.rdf4j.org/programming/#_validation_with_shacl_experimental).

**Pull request merged**
