### PR TITLE
docs (webapi): getting started docs

### LINKED ISSUE #351: Documentation
Please complete the documentation about the triplestore configuration. I found only a TODO on [Choosing and Setting Up a Triplestore](http://www.knora.org/documentation/manual/rst/knora-api-server/deployment/webapi-getting-started.html#choosing-and-setting-up-a-triplestore)

> Creating a Test Installation
> TODO: write subsections like this:
> - Download the Knora API Server and Sipi from GitHub
> - Configure
> - Run

### PR DESCRIPTION
**Pull request by subotic**
### Summary

 - resolves #351

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@kilchenmann Is that clear enough for you? Is more info needed?

**Comment by kilchenmann** [comment]
Yeah, I think that's fine

**Comment by subotic** [comment]
@tobiasschweizer can I merge this?

**Comment by subotic** [comment]
Thanks :-)

**Pull request merged**
