### PR TITLE
Fix inconsistencies in incunabula-demo-data.ttl.

### LINKED ISSUE #405: Incunabula-demo-data.ttl doesn't pass the consistency checking
We can't have the incunabula-demo-data.ttl pass the consistency checking.
Is it expected?

We have fixed what appear to be several mistakes, but it looks like there are some more...

graphdb 8.0.3
Incunabula-demo-data.ttl 81dfe00dee95485d41ef58419c52994645eea080

### PR DESCRIPTION
**Pull request by benjamingeer**
Fixes #405.

* Ran `incunabula-demo-data.ttl` through `TransformData -t all`.
* Added missing `valueHasCreationDate`.
* Added text to fix empty strings.
* There were many references to sidebands, but no actual sidebands. Removed all references to sidebands.

### CODE REVIEW

**Comment by subotic** [comment]
We created it at the time when we published Knora on Github, so that a potential user would have some demo data that would load in a shorter time, then the full incunabula data.

IMHO we can remove this. We have enough ``ttl`` files that we need to maintain.  We still have ``images-demo.ttl` which could be used for a quick test.

I don't know if Lausanne is using this.

**Comment by mrivoal** [comment]
No, we don't use it. 

I loaded it the last time because I got lost in the .ttl files avaiblable. I wanted to run some tests but I could have done it with incunabula-data.ttl.

**Comment by benjamingeer** [comment]
It's part of the documentation:

http://www.knora.org/documentation/manual/rst/introduction/example-project.html

**Comment by tobiasschweizer** [comment]
Right! Ok, it can be merged then.

**Comment by loicjaouen** [comment]
i don't see a reference to `incunabula-demo-data.ttl` but `incunabula-data.ttl`.

**Comment by tobiasschweizer** [comment]
`store-module.rst`:

```
            {
                path = "_test_data/demo_data/incunabula-demo-data.ttl"
                name = "http://www.knora.org/data/incunabula"
            }
```

**Comment by benjamingeer** [comment]
If you're all happy for the huge `incunabula-data.ttl` to be used in the docs, I'm happy to delete `incunabula-demo-data.ttl`. One less thing to maintain.

**Comment by loicjaouen** [comment]
we are particularly happy with the huge file, but we got side-tracked by the outdated small one.

It is now in sync, fine, let's keep it.
But there is no automated ways to check it, so maintaining it will difficult and chances of lags are high.

**Pull request merged**
