### PR TITLE
Fix: Creation of xpath expression to insert word separator

### LINKED ISSUE #903: Create a custom standoff mapping
Hi,
I try to create a standoff mapping for our project following the steps of this [doc](https://docs.knora.org/paradox/03-apis/api-v1/xml-to-standoff-mapping.html#creating-a-custom-mapping). 
When I send my [data](https://github.com/dhlab-basel/Knora/files/2122849/data.xml.zip) with a bulk import : 
```
curl -u lumieres@unil.ch:test -X POST -d @data.xml http://localhost:3333/v1/resources/xmlimport/http%3A%2F%2Frdfh.ch%2Fprojects%2F0113
```
I get this error:
```json
{
    "status": 4,
    "error": "net.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXParseException; lineNumber: 13; columnNumber: 39; Element type \"xsl:template\" must be followed by either attribute specifications, \">\" or \"/>\"."
}
```
1/ do I have to provide a style sheet related to my mapping, is that the problem ?
2/ is the mapping replace or extend the default existing mapping ?

thx for your help

---

My test case is the following:
```html
<text xmlns="">
 <p>test p tag</p>
 <span class="sic" data-corr="Paris">paris</span>
</text>
```
`<p>` tag is already managed by the default mapping of Knora, so in my mapping I just have to map the `<span>` tag of class _sic_ and store the _data-corr_ string value (meaning a data fix): 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping>
    <mappingElement>
        <tag>
            <name>span</name>
            <class>sic</class>
            <namespace>noNamespace</namespace>
            <separatesWords>true</separatesWords>
        </tag>
        <standoffClass>            
            <classIri>http://www.knora.org/ontology/0113/lumieres-lausanne#StandoffEditionTag</classIri>
            <attributes>
                <attribute>
                    <attributeName>data-corr</attributeName>
                    <namespace>noNamespace</namespace>
                    <propertyIri>http://www.knora.org/ontology/0113/lumieres-lausanne#standoffEditionTagHasFix</propertyIri>
                </attribute>
            </attributes>
        </standoffClass>
    </mappingElement>
 </mapping>
```
```json
{
    "project_id": "http://rdfh.ch/projects/0113",
    "label": "LL Standoff mapping",
    "mappingName": "LLStandoffMapping"
}
```
```
curl -u lumieres@unil.ch:test -X POST -F json=@mappingForLL.json -F xml=@mappingForLL.xml  http://localhost:3333/v1/mapping
```
The custom standoff class:
```turtle
lumieres-lausanne:standoffEditionTagHasFix rdf:type owl:DatatypeProperty ;
                  knora-base:subjectClassConstraint lumieres-lausanne:StandoffEditionTag ;
                  knora-base:objectDatatypeConstraint xsd:string .

lumieres-lausanne:StandoffEditionTag rdf:type owl:Class ;
    rdfs:subClassOf knora-base:StandoffTag,
                   [
                      rdf:type owl:Restriction ;
                      owl:onProperty lumieres-lausanne:standoffEditionTagHasFix ;
                      owl:cardinality "1"^^xsd:nonNegativeInteger
                   ] ;
    rdfs:label "Represents an edition fix in a TextValue"@en.     
```

### PR DESCRIPTION
**Pull request by tobiasschweizer**
There was a bug in how the xpath expression to separate words was created.

resolves #903

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
> What flavour gelato would you like? :)

Let's see first if the tests pass ... :-)

**Comment by tobiasschweizer** [comment]
@gfoo Do the test cases adequately represent your scenario?

**Comment by tobiasschweizer** [comment]
@gfoo yes, we did not have a test case for an element-class combination whee the word separation flag was set to true. Otherwise we would have known :-)

Great that you brought this up, I hope you did not lose much time

**Comment by gfoo** [comment]
obviously :)

**Pull request merged**
