### PR TITLE
Fixes for consistency checking

### LINKED ISSUE #30: Query returns correct results with Fuseki 2.3.0 but not with 2.3.1
https://issues.apache.org/jira/browse/JENA-1130

### LINKED ISSUE #70: FOAF Properties Naming
In ```OntologyConstants``` we have the following:

```
object Foaf {
        val FirstName = "http://xmln.com/foaf/0.1/firstName"
        val LastName = "http://xmln.com/foaf/0.1/lastName"
    }
```

In ```knora-base.ttl``` we have the following definition:

```
###  http://www.knora.org/ontology/knora-base#User

:User rdf:type owl:Class ;
      
      rdfs:subClassOf <http://xmlns.com/foaf/0.1/Person> ,
                      [ rdf:type owl:Restriction ;
                        owl:onProperty <http://xmlns.com/foaf/0.1/familyName> ;
                        owl:cardinality "1"^^xsd:nonNegativeInteger
                      ] ,
                      ...
                      [ rdf:type owl:Restriction ;
                        owl:onProperty <http://xmlns.com/foaf/0.1/givenName> ;
                        owl:cardinality "1"^^xsd:nonNegativeInteger
                      ], 
                      ...
      
      rdfs:comment "Represents a Knora user"@en .
```

According to the [FOAF](http://xmlns.com/foaf/spec/) spec, we have these options: ```foaf:givenName``` which is used alongside ```foaf:familyName``` and ```foaf:firstName```which is used alongside ```foaf:lastName```. The spec prefers the givenName / familyName combination.

I suppose that we should then stick to ```foaf:givenName``` / ```foaf:familyName```?

Also there is a mix of both usages in the test/demo data, which I would like to clean up as soon as it is clear what we will use.

@lrosenth 
@benjamingeer 
@tobiasschweizer

### PR DESCRIPTION
**Pull request by benjamingeer**
This pull request introduces GraphDB rules for consistency checking (disabled for now because of problems described in issue #33), and fixes a lot of things in ontologies, test data, tests, and `webapi` code that violated consistency constraints. I'd like to merge this because it would be good to have the corrected ontologies and tests in `develop`, even though we can't enable consistency checking yet.

The consistency checking configuration and rules are documented under `Consistency Checks` in `triplestore-updates.rst`.

Ontology fixes include:

* Fix incorrect `knora-base:subjectClassConstraint` of `knora-base:resourceIcon`.
* Rename `knora-base:basepath` to `knora-base:projectBasepath` and `knora-base:shortname` to `knora-base:projectShortname`, to match what's in the test data.
* Add `projectLongname`, `projectKeyword`, and `projectLogo` to `knora-base`, as used in the test data.
* Fix a typo in the IRI used for the `foaf` prefix.
* Allow `knora-base:hasComment` to be used with values as well as resources, because that's how we've been using it.
* Fix incorrect `knora-base:subjectClassConstraint` on properties whose subject should be a `knora-base:FileValue` (not a `knora-base:Representation`).
* Fix `knora-base:subjectClassConstraint` of `knora-base:standoffHasAttribute` to allow it to be used with `knora-base:StandoffLink` as well as `knora-base:StandoffVisualAttribute`, because that's how it's used in the test data and in Knora. Its `subjectClassConstraint` is now the base class, `knora-base:Standoff`.
* Remove the cardinality for `knora-base:valueHasString` from `knora-base:Value`, because `LinkValue`s don't have this property in the test data, and I think it wouldn't make sense for them to have it (it's not clear to me what it would contain, and I don't think users would want to see it or search for it). Instead, add this cardinality to the subclasses of `Value` for which it seems to make sense.
* Fix cardinalities on `knora-base:ListNode` so that root nodes aren't required to have predicates that only non-root nodes have.
* Use `foaf:givenName` and `foaf:familyName` instead of `foaf:firstName` and `foaf:lastName` (closes #70).

In the test data, everything that violated consistency constraints has been removed. Several tests that depended on inconsistent data (e.g. tests in `ValuesResponderV1Spec` that required a resource with missing values) have been changed to respect consistency constraints (e.g. by creating a new resource class in which everything is optional).

All the test data files that are loaded by unit tests now pass consistency checks, and the tests themselves pass with consistency checking disabled. Many of the tests can't work with consistency checking enabled until the issues in #33 are resolved, which is why it's disabled for now.

Issue #62 deals with relevant bugs in the export script and/or in the original project data that the test ontologies and data are based on.

The scripts `fuseki-load-test-data.sh` and `graphdb-se-load-test-data.sh` now load both `incunabula` and `images-demo` ontologies and data.

All the repository-creation scripts now expect to be run from the directory where they are located rather than from the top-level directory, for consistency with `_fuseki/fuseki-server`.

There is also a fix here that closes #30 (getting correct query results with Jena 3.0.1).

### CODE REVIEW

**Comment by subotic** [comment]
Looks good. Please go ahead and merge.

Small suggestion, when at a later time consistency checking is turned on, it would be nice to have an explicit spec that checks that all the rules work.

**Comment by subotic** [comment]
I will just go ahead an merge it.

**Comment by benjamingeer** [comment]
> when at a later time consistency checking is turned on, it would be nice to have an explicit spec that checks that all the rules work.

Definitely.

> I will just go ahead an merge it.

Thanks!

**Comment by subotic** [comment]
faster ;-)

**Pull request merged**
