### PR TITLE
fix (webapi): image permission

### LINKED ISSUE #1003: After an image has been uploaded, the user is unable to see it (only RV)
Using Salsah 1.5, after a user has uploaded an image (i.e. `anything.admin@example.org` creating a `anything:Dingbild`), he is unable to view it properly afterwards. 

The image is only available to him in restricted view. 

It looks like there is a bug in permissions that didn't exist before.

### LINKED ISSUE #1086: Make preview image URLs returned by make_thumbnail configurable

### LINKED ISSUE #1091: Sipi should use Knora's session cookie
Sipi should use Knora's session cookie for authentication, which is sent to Sipi anyway for each request and not open a separate session.

### PR DESCRIPTION
**Pull request by subotic**
### Issues

- resolves #1003 
- resolves #1086 
- resolves #1091

### CODE REVIEW

**Comment by subotic** [comment]
`webapi` is not the problem. Added tests to check `v1/files` route and it seems to work as it should.

**Comment by subotic** [comment]
There is a problem with `Sipi` where the threeway authentication (Salsah -> Sipi -> webapi) over the cookie is not working as it should.

**Comment by gfoo** [comment]
is this pull request also related to #520 ?

**Comment by subotic** [comment]
No, if I get the cookies again to work with Sipi. If not, then I will enable JWT but only for V1 of the API, so that Salsah1 can work correctly. Work will commence on #520 in January and will incorporate V1 and V2 of the API. But there we still have to find a solution that is compatible with generic IIIF viewers (Mirador, etc.).

**Comment by mrivoal** [comment]
Yes, thanks @subotic !

**Comment by subotic** [comment]
> Could you also update the design docs

Yes, will do that.

**Pull request merged**
