### PR TITLE
feature (webapi): admin fixes 3

### LINKED ISSUE #17: Sesame/GraphDB bug affecting the import of carriage returns
When we import RDF data containing a triple-quoted string that ends with a carriage return, the carriage return is stripped, apparently by Sesame:

https://openrdf.atlassian.net/browse/SES-425?jql=text%20~%20%22carriage%20return%22

https://openrdf.atlassian.net/browse/SES-1736?focusedCommentId=14423&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14423

It may be fixed in Sesame 2.7.9, in which case the fix should appear in GraphDB 7.0, which will use Sesame 2.8:

http://graphdb.ontotext.com/documentation/standard/roadmap.html

### LINKED ISSUE #372: Supplying an unknown email address during authentication returns wrong status code
Supplying an unknown email address during authentication should return '401 Unauthorized' and not '404 Not Found'.

There is a problem in ``Authenticator.getUserProfileByEmail``

### LINKED ISSUE #416: Some help wanted for implementing complex permissions
1. I defined `AdministrativePermissions` for every group of my project.
2. I defined `DefaultObjectAccessPermission` on every group because generally speaking we don't want lower access group to update data created by higher lever access group
3. I defined `DefaultObjectAccessPermission` for every class of the project (every group is not granted the same access on thoses classes)
4. I defined `DefaultObjectAccessPermission` for some properties because, even for classes widely accessible, some data are considered sensitive and should be restricted to the core research group (**SNFteam** group).

However, I don't get the result I expected. 

In **1**, I expected instances of **QualityData** to have the `DefautObjectAccessPermission` defined for its resource class - not the one inherited from the group its creator belongs to.

In **2**, I expected the value of the **hasLastname** property to inherit the `DefautObjectAccessPermission` set for this property - not the one inherited from the group its creator belongs to.

In **2**, given what happened in **1**, I did not expect the instance of **Person** to inherit the `DefautObjectAccessPermission` set for the class **Person**, instead of the one inherited from the group its creator belongs to.

I am obviously doing something very wrong. So please, could you help me ? 

# 1
 Within Drawings-gods project, I have a user **ddd** : 

```
<http://data.knora.org/users/drawings-gods-test-ddd> a knora-base:User ;
        knora-base:userid "ddd"^^xsd:string ;
        knora-base:givenName "ddd"^^xsd:string ;
        knora-base:familyName "ddd"^^xsd:string ;
        knora-base:password "******"^^xsd:string ;
        knora-base:email "ddd@unil.ch"^^xsd:string ;
        knora-base:preferredLanguage "fr"^^xsd:string ;
        knora-base:status "true"^^xsd:boolean ;
        knora-base:isInProject <http://data.knora.org/projects/drawings-gods> ;
        knora-base:isInProjectAdminGroup <http://data.knora.org/projects/drawings-gods> ;
        knora-base:isInGroup <http://data.knora.org/groups/drawings-gods-snf-team> ;
        knora-base:isInSystemAdminGroup "false"^^xsd:boolean .
```

The **SNFteam** group he belongs to has a `DefautObjectAccessPermission`:

```
### Default Object Access Permissions on SNFTeam Group 
<http://data.knora.org/permissions/drawings-gods-o004> rdf:type knora-base:DefaultObjectAccessPermission ;
     knora-base:forProject <http://data.knora.org/projects/drawings-gods> ;
     knora-base:forGroup <http://data.knora.org/groups/drawings-gods-snf-team> ;
     knora-base:hasPermissions "RV knora-base:UnknownUser,knora-base:KnownUser|V knora-base:ProjectMember|M <http://data.knora.org/groups/drawings-gods-meta-annotators>,<http://data.knora.org/groups/drawings-gods-add-drawings>|D <http://data.knora.org/groups/drawings-gods-snf-team>, knora-base:Creator|CR knora-base:ProjectAdmin"^^xsd:string .
```
*(I defined it because it is the general behaviour expected for resources created by this group. However, restrictions apply on some resources and properties.)*

The **SNFteam** group creates a resource **QualityData** with access restricted to some users groups within the project . See **QualityData** resource class `DefaultObjectAccessPermission` :

```
### Default Object Access Permissions on resource class QualityData
<http://data.knora.org/permissions/drawings-gods-o020> rdf:type knora-base:DefaultObjectAccessPermission ;
     knora-base:forProject <http://data.knora.org/projects/drawings-gods> ;
     knora-base:forResourceClass <http://www.knora.org/ontology/drawings-gods#QualityData> ;
     knora-base:hasPermissions "M <http://data.knora.org/groups/drawings-gods-meta-annotators>,<http://data.knora.org/groups/drawings-gods-add-drawings>|D <http://data.knora.org/groups/drawings-gods-snf-team>,knora-base:Creator|CR knora-base:ProjectAdmin"^^xsd:string .
```

However, after the **QualityData** instance is created, it gets the following permission : 

```
"CR knora-base:ProjectAdmin|D <http://data.knora.org/groups/drawings-gods-snf-team>,knora-base:Creator|M <http://data.knora.org/groups/drawings-gods-meta-annotators>,<http://data.knora.org/groups/drawings-gods-add-drawings>|V knora-base:ProjectMember|RV knora-base:KnownUser,knora-base:UnknownUser"
```

# 2
This topic is probably a variation of the first one, but I have the same issue with the property **hasLastname**, attached to a class **Person**.

Here is the `DefaultObjectAccessPermission` on the class **Person** :

```
### Default Object Access Permissions on resource class Person
<http://data.knora.org/permissions/drawings-gods-o019> rdf:type knora-base:DefaultObjectAccessPermission ;
     knora-base:forProject <http://data.knora.org/projects/drawings-gods> ;
     knora-base:forResourceClass <http://www.knora.org/ontology/drawings-gods#Person> ;
     knora-base:hasPermissions "V knora-base:UnknownUser,knora-base:KnownUser,knora-base:ProjectMember|M <http://data.knora.org/groups/drawings-gods-meta-annotators>,<http://data.knora.org/groups/drawings-gods-add-drawings>|D <http://data.knora.org/groups/drawings-gods-snf-team>,knora-base:Creator|CR knora-base:ProjectAdmin"^^xsd:string .
```

And here is the `DefaultObjectAccessPermission` on the property **hasLastName** (because it is considered a sensitive data) : 

```
### Default Object Access Permissions on hasLastname
<http://data.knora.org/permissions/drawings-gods-o102> rdf:type knora-base:DefaultObjectAccessPermission ;
     knora-base:forProject <http://data.knora.org/projects/drawings-gods> ;
     knora-base:forProperty <http://www.knora.org/ontology/drawings-gods#hasLastname> ;
     knora-base:hasPermissions "D <http://data.knora.org/groups/drawings-gods-snf-team>|CR knora-base:ProjectAdmin"^^xsd:string .
``` 
After the **ddd** user created an instance of **Person**, this instance gets the following permission :

```
CR knora-base:ProjectAdmin|D <http://data.knora.org/groups/drawings-gods-snf-team>,knora-base:Creator|M <http://data.knora.org/groups/drawings-gods-meta-annotators>,<http://data.knora.org/groups/drawings-gods-add-drawings>|V knora-base:KnownUser,knora-base:UnknownUser,knora-base:ProjectMember
```

*(So, for this resource class, the instance gets the `DefaultObjectAccessPermission` of the class **Person**, not the one from **SNFteam** group.)*

but the permission on the value of **hasLastName** property is

```
CR knora-base:ProjectAdmin|D <http://data.knora.org/groups/drawings-gods-snf-team>,knora-base:Creator|M <http://data.knora.org/groups/drawings-gods-meta-annotators>,<http://data.knora.org/groups/drawings-gods-add-drawings>|V knora-base:ProjectMember|RV knora-base:KnownUser,knora-base:UnknownUser
```
So, here, it is again the `DefaultObjectAccessPermission` of the **SNFteam** group that applies. I don't understand why here the group's permission prevails on the resource class `DefaultObjectAccessPermission` (even if I originally intended it to inherit the `DefaultObjectAccessPermission`  set up for the property).

# 3 

I guess this rule applies a some point, right?  :

> If the user creating a new object is a member of more than one group with such attached permissions, and additionally default object access permission are defined on resource classes and/or properties, then the final set of default object access permissions that will result is additive and most permissive.

But in **2**, the `DefaultObjectAccessPermission` on the resource class **Person** is more permissive than the one on the creator's group. So why/how does the value of **hasLastName** property get the `DefaultObjectAccessPermission` of the creator's group? 

---

Finally, how should I set up permissions in order to have an instance of **QualityData** with this permission : 

```
M <http://data.knora.org/groups/drawings-gods-meta-annotators>,<http://data.knora.org/groups/drawings-gods-add-drawings>|D <http://data.knora.org/groups/drawings-gods-snf-team>,knora-base:Creator|CR knora-base:ProjectAdmin
```

And how should I set up `DefautObjectAccessPermission` to have values of **hasLastname** property with this permission : 

```
D <http://data.knora.org/groups/drawings-gods-snf-team>|CR knora-base:ProjectAdmin
```

It is even possible while keeping `DefautObjectAccessPermission` on **SNFteam** group ?

### LINKED ISSUE #419: Return all members of a project
The routes ``v1/projects/iri/<projectIri>`` and ``v1/projects/shortname/<shortname>`` should return all project members.

### LINKED ISSUE #460: List of Users
How do I get a list of every user? I need it in the new admin interface.

### PR DESCRIPTION
**Pull request by subotic**
### Summary

- Default Object Access Permission (DOAP) precedence
- DOAP for resource class and property combination
- Project members

### Issues

 - resolves #17
 - resolves #372
 - resolves #416 
 - resolves #419 
 - resolves #460

### CODE REVIEW

**Comment by subotic** [comment]
Sure, no problem. I wanted to do it anyway, but you where faster. :)

**Comment by subotic** [comment]
thanks. also ready for re-review :)

**Comment by subotic** [comment]
thanks :-)

**Comment by subotic** [comment]
@loicjaouen is it OK to delete this branch?

**Comment by subotic** [comment]
@loicjaouen is it ok to delete the branch `wip/admin-fixes-3`?

**Comment by loicjaouen** [comment]
sure! thanks ;)

**Pull request merged**
