### PR TITLE
replacing a "&nbsp;" by its character

### LINKED ISSUE #494: [Salsah 1.5] [CKeditor] - support for non breakable space
CKeditor should support the `&nbsp;` character.

### PR DESCRIPTION
**Pull request by loicjaouen**
fixes #494

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
Have you run the browser tests?

**Comment by loicjaouen** [comment]
the browser test... I forgot, I do so and will be right back

**Comment by loicjaouen** [comment]
finally, here it is:

```
[info] Run completed in 1 minute, 34 seconds.
[info] Total number of tests run: 28
[info] Suites: completed 3, aborted 0
[info] Tests: succeeded 28, failed 0, canceled 0, ignored 1, pending 0
[info] All tests passed.
```

**Comment by loicjaouen** [comment]
thanks :)

**Pull request merged**
